### ISSUE TITLE
S3 Upload Task: "Bucket does not exist" masking SSL certificate validation error

### ISSUE THREAD

**Issue by shieldsjared** [aws/aws-vsts-tools#10]
New to using AWS and these tasks (thanks for creating them!).  Im having trouble using the "S3 Upload" task, yet using the CLI directly to upload is working fine.

Using the S3 Upload task, I receive the error: 
![image](https://user-images.githubusercontent.com/600643/29939802-221bb45e-8e5b-11e7-9dff-3191164d614b.png)

The configuration is as follows:
![image](https://user-images.githubusercontent.com/600643/29939829-3c73e7f4-8e5b-11e7-801f-d6b46ac8b011.png)

I'd ideally like to use the simple S3 task as it's easier to manage with straight forward properties specific to the task... The CLI task works, but not as straight forward to maintain.

It's worth mentioning that I am using an account with very limited access to the bucket; however, since it works successfully using `aws s3 cp`, it stands to reason that the S3 Upload task should work...

Thoughts?  Thanks for your time!

**Comment by incarnate** [comment]
Before uploading to your S3 bucket, the script checks if it exists with a [HEAD Bucket](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketHEAD.html) request ([here](https://github.com/aws/aws-vsts-tools/blob/master/Tasks/S3Upload/helpers/taskOperations.ts#L65)).

While your account may have access to upload to the bucket, it is likely it doesn't have the `s3:ListBucket` permission needed to check it exists.

**Comment by normj** [comment]
As @incarnate side the task does do a head check to make sure the bucket exists. You might find this previously closed issue helpful https://github.com/aws/aws-vsts-tools/issues/5

**Comment by shieldsjared** [comment]
@normj - Turns out that I have the permissions required.  I tried using the `s3api head-bucket` cli command with success.  

I did some tests and found the problem is due to SSL verification... And I think this task might be causing the problem.  Looking at the code, I see the following:

```
        try {
            await this.s3Client.headBucket({ Bucket: bucketName}).promise();
            return true;
        } catch (err) {
            return false;
        }
```

Turns out that the `headBucket(...)` is failing with the following error:

'UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): NetworkingError: unable to get local issuer certificate'

Some possible improvements could be:
- Adding a configuration parameter to disable strict ssl
- Checking for that specific error (shown above)
- Checking for the expected 404 that confirms the bucket doesn't exist and reporting all other errors for clarity
- Denying any change and relying on environmental configuration changes

What are your thoughts?  I'm happy to submit a PR, but I'm not sure which solution would be preferred...

**Comment by shieldsjared** [comment]
@normj - Just circling back - do you want a PR for this fix?

**Comment by normj** [comment]
I suspect if you got past the head bucket error you would just get another error on the put for the SSL. Out of curiosity does your bucket have periods in it?

**Comment by shieldsjared** [comment]
Great point, @normj.  The ideal solution would require an end-to-end fix that disabled the SSL verification for the put as well.

Periods: yes, the bucket has periods.

In the end - hoping we can come up with a solution to this that enables the use of the S3 Upload task in w/o ssl verification.  I'm using the CLI task in the meantime, and simply appending the `--no-verify-ssl` flag... but its not as straightfoward for other folks to maintain.

**Comment by hunterwerlla** [comment]
Closing this in favor of https://github.com/aws/aws-vsts-tools/issues/132 which tracks the feature request that would fix this issue.
