### ISSUE TITLE
SQS Create-Queue QueueUrl to Output Variable 

### ISSUE THREAD

**Issue by JulioIzquierdo** [aws/aws-vsts-tools#102]
Using VSTS and AWS CLI extension, I am creating a queue and need to get the QueueURL for assigning further in the task pipeline.
Is there a way to output the QueueUrl to an VSTS Output Variable?

**Comment by steveataws** [comment]
Although [this link](https://gist.github.com/DavidDeSloovere/3292ac31649e479d141d67cd14eaaabf) uses PowerShell, it shows how you can create a build variable by writing to the console using a formatted string. Hopefullyt this will get you started.

**Comment by steveataws** [comment]
Closing as I don't believe there is any task related work for us to do here. Feel free to reopen if not the case.
