### ISSUE TITLE
AWS Endpoint configuration from vsts 

### ISSUE THREAD

**Issue by yaminipavani** [aws/aws-vsts-tools#105]
This is regarding the vsts aws serviceendpoint configuration, presently we are using access and secureID for establishing the connection and using aws tools , we are planning to use the IAM role instead of accessid and secureid, i have checked couple of the articles, where calling the restapi of service endpoint and embed in code, but taht approch takes time, i would request to suggest a article like iam roles which can be configured for vsts and use the aws servcies

**Comment by steveataws** [comment]
The tools already support using an IAM role when configuring an endpoint. I haven't reviewed the docs lately for this area so I don't know immediately how spare or complete it is. Usually the docs are sourced and expanded upon from the tooltip help that you can get in the endpoint configuration dialog itself.

**Comment by yaminipavani** [comment]
Can you please refer me to the tooltip which you are referring to



Sensitivity: Internal & Restricted

**Comment by steveataws** [comment]
When you are in the endpoint configuration dialog, at the right of each field is a small blue circle with what appears to be an 'i' inside it - hovering over this will display the help text for the field.

You can see an example of the indicator in the [docs](https://docs.aws.amazon.com/vsts/latest/userguide/getting-started.html).

**Comment by hunterwerlla** [comment]
There seems to be no movement on this ticket, closing
