### ISSUE TITLE
Add configuration for VSTS Build and Deploy to ElasticBeanstalk to set the pull rate to minimize the throttle exceeded error

### ISSUE THREAD

**Issue by jaydinslage** [aws/aws-vsts-tools#115]
Currently, due to our setup, our builds in certain regions regularly encounter the "Throttling: Rate Exceeded" error when deploying to ElasticBeanstalk. After many discussions with our admins, the cost of changing our setup outweighs our resolving the issue with creating more accounts.

So, to minimize the possibility of receiving this issue, I'm requesting that we be able to configure the rate at which the deploy task pulls for status's from AWS. The idea is that I can say "Check for status every 5 or 10 seconds". This would limit the number of requests to AWS and thereby reducing the possibility of receiving the exception.

**Comment by steveataws** [comment]
Sure, that can be done. The lower limit would obviously be the current polling interval - no sense in potentially increasing throttle errors - but what upper limit would work for you?

**Comment by jaydinslage** [comment]
Awesome! Thank you. It doesn't need to be anything excessive. Since releasing to beanstalk doesn't take a long time, I'd say an upper value could be anywhere from 30 seconds to a minute. I'm thinking that I'd set it to every five or ten seconds.

**Comment by steveataws** [comment]
v1.1.7 is now released which contains the new option to control the polling delay. Resolving the issue, feel free to reopen if it doesn't work as expected or you need a longer delay period (I set 5secs to 5mins).
