### ISSUE TITLE
EC2 Deployment keeps failing

### ISSUE THREAD

**Issue by timgabrhel** [aws/aws-vsts-tools#12]
I've verified the artifact output of a build is clean and not adding this element into the config, as I'd expect. However, once the EC2 deployment task, within a *release* runs, the package that is uploaded to S3 for the deployment contains a rogue rewrite url. This is giving us 500's and removing this section, the application works fine.

```
<rule name="AWS_BEANSTALK" stopProcessing="false">
     <match url="^(https?://[^/]+/)MyProject.Web_deploy" ignoreCase="true" negate="true" />
          <conditions>
               <add input="{PATH_INFO}" pattern="^/MyProject.Web_deploy" negate="true" />
          </conditions>
          <action type="Rewrite" url="{R:1}MyProject.Web_deploy{PATH_INFO}" logRewrittenUrl="true" /></rule>
```

**Comment by timgabrhel** [comment]
This seems like it may be part of the typical web deploy process, I'm not sure. What we ended up having as our issue is the standard web deploy package was trying to deploy the IIS site into `Default Web Site/Autogenerated_package_name`, however, our app needs to be deployed into `Default Web Site`. 

The fix we applied was the MSBuild parameter `/p:DeployIisAppPath="Default Web Site/"` to set the path.

**Comment by normj** [comment]
Beanstalk just applies the package as a webdeploy bundle including any rules that are embedded in the package. There is nothing in the task we can to do to about that so make sure the package bundle has all the web deploy configuration you want.
