### ISSUE TITLE
AWS AWS Elastic Beanstalk Deploy Application Task Permissions are incorrect

### ISSUE THREAD

**Issue by whoiskevinrich** [aws/aws-vsts-tools#124]
In addition to the currently listed permissions, we found the following were also needed to deploy an elastic beanstalk application:

- autoscaling:SuspendProcesses
- cloudformation:DescribeStackResource
- cloudformation:DescribeStackResources
- autoscaling:DescribeAutoScalingGroups
- autoscaling:DescribeScalingActivities
- autoscaling:ResumeProcesses
- elasticloadbalancing:RegisterInstancesWithLoadBalancer

We found we could push the application to the beanstalk, but some other tasks were failing upon application setup, causing the deployment to fail.

The documentation currently shows the following permissions are needed:

- elasticbeanstalk:CreateApplicationVersion
- elasticbeanstalk:CreateStorageLocation
- elasticbeanstalk:DescribeApplications
- elasticbeanstalk:DescribeEnvironments
- elasticbeanstalk:DescribeEvents
- elasticbeanstalk:UpdateEnvironment

**Comment by steveataws** [comment]
Thanks for letting us know. I've updated the task documentation and the change will be included in the next release.

**Comment by steveataws** [comment]
New task help for reference: 
![image](https://user-images.githubusercontent.com/2090449/48574951-6b3a8a00-e8c5-11e8-8466-257335a8b549.png)

**Comment by hunterwerlla** [comment]
This is released as of the 1.2.0 release
