### ISSUE TITLE
CloudFormation : Support for --use-previous-template 

### ISSUE THREAD

**Issue by steven-cuthill-otm** [aws/aws-vsts-tools#127]
Quick feature request, Template Source = Use Previous Template
alow the user to set the Template Source to Use Previous Template. this will remove the need to select / upload a template and the CLI will update the stack with the parameters and --use-previous-template  argument.  

This is handy when you just want to update the stack params and NOT change the template.

**Comment by steveataws** [comment]
This is implemented pending release, I forgot to update the issue when I finished the work.

**Comment by hunterwerlla** [comment]
This is now released as part of 1.2.0 @steven-cuthill-otm
