### ISSUE TITLE
AWS Elastic Beanstalk Deploy Application SolutionName_Deploy

### ISSUE THREAD

**Issue by chaseramone** [aws/aws-vsts-tools#131]
When I perform a publish using TFS with the below settings it will peform the deployment, however, the final url ends up as:
http://magiqdocumentshelp-test.ap-southeast-2.elasticbeanstalk.com/Magiq.DocumentsHelp_deploy
instead of
http://magiqdocumentshelp-test.ap-southeast-2.elasticbeanstalk.com

When I do a publish to beanstalk from within Visual Studio it works as expected. Any ideas would be appreciated.
![aws-configuration](https://user-images.githubusercontent.com/45472599/49259960-85f92b00-f48f-11e8-9fd7-8e46d2a83ff3.PNG)

**Comment by chaseramone** [comment]
My appologies, this is a non issue. 

I missed the /p:DeployIisAppPath="Default Web Site/" from the build definition.

**Comment by Raraku** [comment]
Hi, I don't think this is fixed.
I uploaded a zip archive directly to elastic beanstalk and it sticks to deploying with APP_DEPLOY as a prefix.
Using a deployment manifest gets it to work but then environmental variables are no longer fed into configuration manager
