### ISSUE TITLE
Add support for the new Lambda Layers (re:Invent 2018) feature

### ISSUE THREAD

**Issue by steveataws** [aws/aws-vsts-tools#133]
Need to extend the generic Lambda deployment task so that it can support specifying a list of 0 or more layers for the function configuration.

**Comment by hunterwerlla** [comment]
This was added as part of the 1.5 release.

**Comment by mpuigdomenchSage** [comment]
Hi , one quick question is also the support for the layers added on the LambdaNETCoreDeploy task ? thanks !

**Comment by hunterwerlla** [comment]
@mpuigdomenchSage can you file a feature request
