### ISSUE TITLE
Using EC2 instance role of the pipeline agent to assume a role in another account

### ISSUE THREAD

**Issue by jeffrey-opdam** [aws/aws-vsts-tools#136]
Hi,

I am hosting the pipeline agents in a AWS account. I went through the documents about cross-account roles and assume role.
I did a few tests where I assumed a role of another AWS account on our EC2 instance, without needing the master access key id and access secret key by attaching a instance role with permissions to assume a role.

I want to achieve the same when deploying to aws, but the access key id and access secret key fields are mandatory in the service end point and looking through the code, I am getting the impression that this use case is currently not accounted for.

But I see a work around, where another tasks queries the AWS STS assume-role end point and populates the correct environment variables.

Do you guys/girls/robots have any advice in this matter?

Regards,
Jeffrey Opdam

**Comment by steveataws** [comment]
For build agents that are not hosted on EC2 instances, you can set up the assume role details in the service endpoint definition. As you noted, the access and secret key are required, but you can also specify the role to be assumed. When used with tasks, the endpoint will cause a request to STS to assume the specified role and yield temporary credentials that will then be used by the task. The 'master' access and secret key specified are only used to permit the call to AssumeRole.

If your agents are running on an EC2 instance then the role associated with the instance can also be used by the tasks by simply not referencing an endpoint in a task's configuration (this capability was added in the update this past August). The task can also auto-detect the region the api calls it makes should use from the EC2 instance metadata too.

Of course if none of this works then you could, as you mention, run a custom task to fetch temporary credentials from source and post the the keys and token into environment variables or task variables that will then be consumed by downstream tasks. More details on these variables can be found in this [blog post](https://aws.amazon.com/blogs/developer/updates-to-the-aws-tools-for-visual-studio-team-services/).

This all requires you to be using VSTS (Azure DevOps) or TFS versions 2017 or higher. TFS2015 doesn't support assumed role, as the service endpoint configuration page doesn't recognize that the role data is optional.

**Comment by svisagie** [comment]
What is the ETA on this change described above to allow fixing this issue?

**Comment by hunterwerlla** [comment]
The question seems to have been answered, so closing
