### ISSUE TITLE
AWS CLI: No way to retrieve the output of AWS CLI Task

### ISSUE THREAD

**Issue by ridsmuglani** [aws/aws-vsts-tools#141]
Hi,

I am trying to create a Role using AWS CLI task in Azure Devops. I need to check if the role already exists before I try to create it. I am unable to see a way to retrieve the output of a Get-Role command or any other way to figure out if a role exists. 
Please help.

**Comment by awschristou** [comment]
Could you use some Powershell to query the role, for example
`Get-IAMRoleList | Where-Object -Property RoleName -eq -Value "SOMEROLENAMEHERE"` ?

**Comment by hunterwerlla** [comment]
@ridsmuglani can you confirm if @awschristou 's solved your issue? thanks!

**Comment by PilotBob** [comment]
I need the output of the CLI as well, in order to get use the ecr get-login do I can run the docker login command. Since there is no AWS ECR Pull task. Of course, that task would also solve my problem.

**Comment by hunterwerlla** [comment]
@PilotBob Can you file a feature request for that as well, thanks

**Comment by PilotBob** [comment]
@hunterwerlla  Done. https://github.com/aws/aws-vsts-tools/issues/169

**Comment by ridsmuglani** [comment]
> Could you use some Powershell to query the role, for example
> `Get-IAMRoleList | Where-Object -Property RoleName -eq -Value "SOMEROLENAMEHERE"` ?

Apologies for a very late reply. I used cloudFormation instead of using out of the box tasks to deploy my artifacts. But for an AWS cli generic task, option for retrieving output should be there.  In its current form its usage is limited.

**Comment by tometchy** [comment]
It's still not fixed, but I found even better way to use AWS CLI in Azure DevOps pipelines - there is a task called _AWS Shell Script_ which allows you to run any bash script you want being authorized to AWS and having aws cli inside, and even do for example output redirection and some actions based on that:
``` bash
aws ecr describe-images --repository-name=some-repo --image-ids=imageTag=$(Tag) 2> image-details.txt
if grep -q ImageNotFoundException "image-details.txt"; then
  echo "$(Tag) tag not found"
else
  echo "$(Tag) tag found"
fi
```

It works very well in my case (I'm using M$ hosted agents with ubuntu-22.04).
