### ISSUE TITLE
Outbound Connection to AWS

### ISSUE THREAD

**Issue by kpworld** [aws/aws-vsts-tools#144]
All outbound connections from our servers that execute the Releases are blocked.  I need to explicitly set what the outbound connections are from the AWS-VSTS Tool.

Can that be provided please?

**Comment by kpworld** [comment]
Appears it is sts.amazon.com  .   I want to ensure that, that would be the only one we need to be worried about or if there will be more?

**Comment by steveataws** [comment]
The tools only communicate with the published AWS endpoints, which vary by service. The sts.amazonaws.com endpoint will also be used when temporary time-limited credentials need to be obtained for a role (if that's how your credentials are set up).

The list of public endpoints can be found [here](https://docs.aws.amazon.com/general/latest/gr/rande.html).

**Comment by hunterwerlla** [comment]
Steve's answer should be sufficient to solve your issue, if you have any more questions/issues, please feel free to open another issue.
