### ISSUE TITLE
How to install AWS CLI on VSTS Hosted Linux agent ?

### ISSUE THREAD

**Issue by samuelneff** [aws/aws-vsts-tools#15]
I'm trying to run the AWS CLI on a VSTS hosted linux agent and following the instructions from here:

http://docs.aws.amazon.com/cli/latest/userguide/awscli-install-linux.html

- Download PIP
- Install PIP
- Use PIP to install AWS CLI

Seems simple enough and using the Command Line task in my VSTS release I was able to download and install PIP, but the very next command that attempts to use it fails:

```
##[error]Failed which: Not found pip: null
##[error]undefined failed with error: Failed which: Not found pip: null
```

Full logs below. What am I doing wrong?

Thanks,

Sam

```
##[section]Starting: Download PIP
==============================================================================
Task         : Command Line
==============================================================================
[command]/usr/bin/curl -O https://bootstrap.pypa.io/get-pip.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1558k  100 1558k    0     0  1884k      0 --:--:-- --:--:-- --:--:-- 1886k
##[section]Finishing: Download PIP
##[section]Starting: Install PIP
==============================================================================
Task         : Command Line
==============================================================================
[command]/usr/bin/python get-pip.py --user
Collecting pip
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB)
Collecting setuptools
  Downloading setuptools-36.4.0-py2.py3-none-any.whl (478kB)
Collecting wheel
  Downloading wheel-0.30.0-py2.py3-none-any.whl (49kB)
Installing collected packages: pip, setuptools, wheel
Successfully installed pip-9.0.1 setuptools-36.4.0 wheel-0.30.0
##[section]Finishing: Install PIP
##[section]Starting: Install AWS CLI
==============================================================================
Task         : Command Line
==============================================================================
##[error]Failed which: Not found pip: null
##[error]undefined failed with error: Failed which: Not found pip: null
##[section]Finishing: Install AWS CLI
##[section]Finishing: Release
```

**Comment by incarnate** [comment]
VSTS runs every task in a fresh session, so changes to the PATH don't persist between tasks. To work around that, you can do a global install instead. 

I tested using the below in the Shell++ task that comes with [Release Management Utility tasks](https://marketplace.visualstudio.com/items?itemName=ms-devlabs.utilitytasks):

```
echo 'Installing AWS'
curl -O https://bootstrap.pypa.io/get-pip.py
python3 get-pip.py
pip --version
pip install awscli --upgrade
aws --version
```

**Comment by Rabadash8820** [comment]
@incarnate I tried using that exact same sequence of commands in a Shell++ task like you suggested, but unfortunately I'm getting the following error: `D:\a\1\s/user_script.sh: /c/Program Files (x86)/Microsoft Visual Studio/Shared/Python36_64/Scripts/aws: c:\program: bad interpreter: No such file or directory`.  It looks to me like these commands don't put `aws` on the PATH either, or am I just missing something?

**Comment by renanlq** [comment]
Thanks @incarnate , here works with Command Line Task to our VSTS Linux Agent, even in preview.
Best regards.

**Comment by joaoasrosa** [comment]
For the new versions needs to be something like:
```
echo 'Installing AWS'
curl -O https://bootstrap.pypa.io/get-pip.py
python3 get-pip.py --user
export PATH="/home/vsts/.local/bin:$PATH"
pip --version
pip install awscli --upgrade --user
aws --version
```

**Comment by JCH01** [comment]
Since the VSTS "Hosted Linux Preview" is going away, I tried switching to "Hosted Ubuntu 1604", tried the script above. The aws version shows correctly, indicating awscli was installed correctly. Still the "AWS CLI Task" that we run afterwards fails with "AWS CLI is not installed on this machine"

**Comment by JCH01** [comment]
In case somebody gets here with the same question...  I went back to my original script, adding "sudo" on the install commands and now everything works as before on "Hosted Ubuntu 1604". So this is working for me:

echo "Installing AWS CLI =========================================="
which python
pip --version
sudo pip install setuptools
sudo pip install wheel
sudo pip install awscli --upgrade
aws --version

[https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azdevops&tabs=yaml]
"If you have scripts that assume that they're running as root, then you'll need to change them to use sudo."

**Comment by ross-bohr** [comment]
Could be simplified to :

sudo pip3 install --upgrade pip
pip3 install awscli --upgrade --user

Works on Hosted Ubuntu 1604

**Comment by pedroswat** [comment]
@ross-bohr This is not working on my setup, on Hosted Ubuntu 1604:
```
sudo pip3 install --upgrade pip
pip3 install awscli --upgrade --user
```

did you do any export to `PATH` after installing aws?

This:
<img width="615" alt="Captura de ecrã 2019-04-15, às 14 01 51" src="https://user-images.githubusercontent.com/29118682/56134721-1344a400-5f87-11e9-975c-48af05312cdd.png">

returns `aws: command not found`

**Comment by Zebirdman** [comment]
i installed the aws cli using the same methods described above, i was able to access the aws command in subsequent scripts by running the export PATH="/home/vsts/.local/bin:$PATH" command again at the start.  As stated by @incarnate changes to the path do not persist between tasks.

**Comment by pedroswat** [comment]
So basically, we have to install `AWS CLI` in each step.
This is my setup for releasing for AWS ECS:

<img width="937" alt="yolo" src="https://user-images.githubusercontent.com/29118682/57762681-d8ee3400-76f7-11e9-8271-9bb7f071a9dc.png">


Thanks all for your help!

**Comment by hunterwerlla** [comment]
We do install for the Powershell modules, so it seems reasonable to add something to do this. Filed task https://github.com/aws/aws-vsts-tools/issues/189 to track it, and closing this one in favor of the feature request task.
