### ISSUE TITLE
CloudFormation CAPABILITY_AUTO_EXPAND not Supported

### ISSUE THREAD

**Issue by jcwhisman** [aws/aws-vsts-tools#150]
We are unable to deploy new CloudFormation templates that use the **Transform** functionality because the VSTS Tools do not support the CAPABILITY_AUTO_EXPAND capability.

Is there currently plans to introduce this to the product? Or are there any workarounds to keep these new CFN templates in our CI/CD pipeline while we wait for the functionality to be added.

Example Error Message:
`2019-04-16T14:46:05.6196545Z ##[error]InsufficientCapabilitiesException: Requires capabilities : [CAPABILITY_AUTO_EXPAND]`

**Comment by hunterwerlla** [comment]
Thanks to @lthorne1 for his PR that fixed this!
https://github.com/aws/aws-vsts-tools/pull/140
