### ISSUE TITLE
Display a "guided tour" upon install or upgrade of the AWS Tools

### ISSUE THREAD

**Issue by pccornel** [aws/aws-vsts-tools#154]
After installing the AWS Tools, it's unclear to know what I should (or even can) do next. I guess I could go see the related documentation over on the AWS website, but I might not know how to get there or even how to navigate the docs once I get there. So, there's an opportunity to provide me with some kind of "Guided Tour" experience right in the middle of the Visual Studio IDE to make sure that I've got the AWS Tools connected to my AWS account and otherwise configured correctly, as well as teach me how to use the AWS Tools to its fullest potential. 

Also, whenever I upgrade the AWS Tools on my dev box and there are new features introduced, the Guided Tour should pop up and show me how to use them. 

Here's how it might work: after installing the AWS Tools for the first time or after upgrading it, a single dialog box should display. This dialog box could include multiple pages that I can flip through, showing things like:

1. What's new in the current release. 
1. Post-install steps, such as connecting the AWS Tools to an AWS account.
1. Embedded how-to videos that briefly walk through key usage scenarios. 
1. Suggested next steps for learning and doing, which link out to related documentation on the AWS website. 

I could quit this Guided Tour at any time. I could also check a box to hide the Guided Tour until the next time I upgrade, in which case it would be shown again, so I could at the very least see what's new in that release. I could also show this dialog again at any time on my own, if desired.

**Comment by hunterwerlla** [comment]
This is a great suggestion, we are investigating this experience.

**Comment by hunterwerlla** [comment]
This is unfortunately not possible for VSTS
