### ISSUE TITLE
AWS Elastic Container Registry Pull

### ISSUE THREAD

**Issue by PilotBob** [aws/aws-vsts-tools#169]
**Is your feature request related to a problem? Please describe.**
In order to build with a Dockerfile that is FROM and ERC image docker needs to be logged into AWS ECR. 

There seems to be no way to get the ECR credentials to login. Hence our Docker build task fails when trying to build our image.

**Describe the solution you'd like**
1. Either a task that allows you to pull an image... it could be build into the Push task or it's own task. This way, we could pull the image, so when Docker build is run, it would see the image is local and not attempt a pull from a repo it isn't logged into.

or

2. A method to do a docker login. One possible way would be to allow to get the output of the AWS CLI so I can then run that comment. Now there is no possible way to do that.

**Describe alternatives you've considered**
Rather than building FROM our base image, merge the two dockerfiles together. This wouldn't require pulling from ECR. However, it would add a large amount of time to build our final image. Or base image takes over 5 minutes to build as it is.

**Additional context**

**Comment by hunterwerlla** [comment]
This has been added as part of the 1.5 release, try it out!
