### ISSUE TITLE
CodeDeployDeployApplication not setting output variable

### ISSUE THREAD

**Issue by svisagie** [aws/aws-vsts-tools#18]
I've found that the CodeDeployDeployApplication task does not set the taskParameters.outputVariable

**Comment by svisagie** [comment]
Added pull request containing proposed fix:

https://github.com/aws/aws-vsts-tools/pull/19

**Comment by normj** [comment]
Thanks for the pull request to fix the issue. I pushed out version 1.0.7 that contains this fix.

**Comment by normj** [comment]
Closing as I believe this is fixed. Feel free to reopen if you are still having issues.

**Comment by svisagie** [comment]
Working perfectly thanks
