### ISSUE TITLE
Proxy Support?

### ISSUE THREAD

**Issue by calebcartwright** [aws/aws-vsts-tools#20]
We're having issues with these tasks when executed on a VSTS Linux agent that is sitting behind a firewall (networking error: connect ENETUNREACH). We've been seeing this with the S3 upload task, but I assume it applies to all tasks. 

The agent has all of the relevant env vars set appropriately and other tasks are leveraging the proxy configuration and successfully executing on the same agent.

Is it possible to run these tasks behind a proxy, and if so, how does the agent need to be configured?

**Comment by steveataws** [comment]
We've not tested using a custom agent in a proxy environment so can't immediately offer any advice on how the agent should be set up, we'll need to set up a test environment to figure it out ourselves. What, if anything, did you need to configure on the other tasks to have them work, and which tasks were those? And what environment variables were you working with?

**Comment by calebcartwright** [comment]
We set the standard environment variables (http_proxy, https_proxy, etc.), the [VSTS agent proxy config](https://github.com/Microsoft/vsts-agent/blob/master/docs/start/proxyconfig.md), and relevant proxy configuration for other tools/tasks (like npm for example) that enable them to reach out. We've got a lot of tasks that are interacting with external systems from our agents through the proxy, but one of the simplest examples would probably be the npm tasks installing dependences from the [npm registry](https://www.npmjs.com/). 

Many of the [default/packaged tasks](https://github.com/Microsoft/vsts-tasks) will leverage proxy settings, an example is [the npm task here](https://github.com/Microsoft/vsts-tasks/blob/bd097c8a7da5508b690690d0f46db18e67ddbe66/Tasks/Npm/npmtoolrunner.ts#L68). There's also tasks which leverage libs which will automatically use the proxy env vars if set, such as [request](https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables)

Also, I know there's a lot of alternatives here (using the hosted build service, running an agent in the public cloud, etc.), but I think it would be useful for these tasks to support proxy config.

**Comment by steveataws** [comment]
Thanks for the info. 

Is the generally accepted usage within VSTS to reach out from tasks to get proxy setup details from the environment, or would users perhaps look to also configure proxy data in the service endpoint setup?

**Comment by calebcartwright** [comment]
@steveataws Good question, I actually don't know if there is a defacto standard. I haven't personally seen any service endpoint types that support proxy configuration. I just went through a few default endpoint types and some that come from extensions and I didn't see any that allowed for proxy input. 

From what I can tell it looks like the usual practice tends to be environment based, but I can definitely see pros & cons to having the service endpoint support it

**Comment by steveataws** [comment]
We just released v1.0.12 which contains support for proxies. The tasks have been updated to accept proxy data configured per the [link](https://github.com/Microsoft/vsts-agent/blob/master/docs/start/proxyconfig.md) you first sent me or by falling back to inspecting HTTP(S)_PROXY environment variables.

Hopefully this resolves the issue for you, so I'm going to close the issue. Feel free to reopen if you hit problems with the new support. And thanks for the feature suggestion!

**Comment by calebcartwright** [comment]
That is awesome! Thanks so much for the quick turn around
