### ISSUE TITLE
Pack script spits RequestExpired error when it take more than 15 minutes 

### ISSUE THREAD

**Issue by shravanjha** [aws/aws-vsts-tools#216]
**Describe the bug**

Running packer script on Private Linux Agent.
It fails if packer takes more than 15 minutes and it works when it takes less than 15 minutes.

![image](https://user-images.githubusercontent.com/3584610/58619571-7c4e6400-8308-11e9-8311-6ee904f5299b.png)

![image](https://user-images.githubusercontent.com/3584610/58619493-5fb22c00-8308-11e9-829a-7a5ed3dcb065.png)

**Expected behavior**
After setting the pipeline variable "aws.rolecredential.maxduration" I expect the session should be still active for one hour.

**Screenshots**

Setting up maxtime duration in azurepipeline as specified below.

![image](https://user-images.githubusercontent.com/3584610/58619396-31345100-8308-11e9-961e-5ff116bc90e3.png)

As per documentation below:

![image](https://user-images.githubusercontent.com/3584610/58619237-d7cc2200-8307-11e9-9196-d5c96db210d3.png)

**Your Environment**
 - Azure Devops (cloud ): 
 - VSTS or Azure Devops version: 
 - AWS VSTS Tools version: 
using latest
![image](https://user-images.githubusercontent.com/3584610/58619321-08ac5700-8308-11e9-96f8-c5c5f3eca294.png)

**Additional context**

**Comment by shravanjha** [comment]
I am using an AWS IAM role which session expiration set to 4 hours.

**Comment by shravanjha** [comment]
I used the logging for variable and it shows below error.
![image](https://user-images.githubusercontent.com/3584610/58620248-f7644a00-8309-11e9-9380-aee8ee848ec5.png)

**Comment by hunterwerlla** [comment]
The issue was easy to find, I'll fix it and it will be in the next release (we are still working on a date for that)
