### ISSUE TITLE
beanstalk deploy VSTS Application app is missing web.config file.

### ISSUE THREAD

**Issue by Neuroforge** [aws/aws-vsts-tools#24]
Hello,

I am using AWS and VSTS.

After creating a .NET core application i was able to upload and deploy. Woohoo!

However, after a few more deployments i can no longer achieve this.

Although a bit out of date, i used this guide as a starting point.
http://docs.aws.amazon.com/vsts/latest/userguide/vsts-ug.pdf

Here is the current error.....

Mon Oct 09 2017 03:20:49 GMT+0000 (Coordinated Universal Time)   INFO   Environment update is starting.
Mon Oct 09 2017 03:20:57 GMT+0000 (Coordinated Universal Time)   INFO   Deploying new version to instance(s).
Mon Oct 09 2017 03:22:00 GMT+0000 (Coordinated Universal Time)   ERROR   Error during deployment: Application app is missing web.config file.

This item is not documented correctly in the PDF linked, and changing it can result in different errors.
Published Application Path

When i choose the dropdown to select a path for this variable it shows me my repo folder structure, and i can choose the sub-directory containing the csproj file. This does not appear to be correct.

Any advice?

Elastic Bean Stalk Instance with IIS default config.
.NET Core 2.0 Application MVC6

Kind regards,

Daniel

**Comment by delphicarlos** [comment]
man, you resolved this problem? Can you post your solution?

**Comment by Neuroforge** [comment]
@delphicarlos I believe i forgot to change my deployment type to dot net core.

**Comment by shashi20170925** [comment]
I set my deployment to dot net core, still seeing the same error.

Here is my output path: --configuration $(BuildConfiguration) --output $(Build.StagingDirectory)\$(Build.BuildNumber).zip
