### ISSUE TITLE
Deploy with Codedeploy task error on 1.2.0

### ISSUE THREAD

**Issue by darshan-emailage** [aws/aws-vsts-tools#249]
```
Task         : AWS CodeDeploy Application Deployment
Description  : Deploys an application to Amazon EC2 instance(s) using AWS CodeDeploy
Version      : 1.2.0
Author       : Amazon Web Services
```

An error occurs with using Codedeploy task.
Error: Application <application name> does not exist

**Comment by kramceel** [comment]
I'm seeing this error also

**Comment by hunterwerlla** [comment]
We have a hotfix to fix this issue: https://github.com/aws/aws-vsts-tools/pull/252 we will be rolling it out as fast as possible

**Comment by kiiadi** [comment]
Duplicate of #251 please use that for tracking.
