### ISSUE TITLE
The default working directory of the AWS Shell Script task has changed with the 1.2/1.3 release

### ISSUE THREAD

**Issue by Cseverance** [aws/aws-vsts-tools#254]
**Describe the bug**
After the extension was updated, all of my AWS Shell Script tasks have started failing. This seems to be related to the default working directory changing from '/home/vsts/work/r1/a' to  '/home/vsts/work/_temp'. 

**To reproduce**
All of my AWS Shell script functions have a pwd command at the start of them. Before the extension update, the pwd command returned /home/vsts/work/r1/a, and after the update it returns /home/vsts/work/_temp. As a result I receive an error when running the intended command The user-provided path _rPractice Serverless Complete Build/drop/build does not exist.

**Expected behavior**
I expected all of my existing tasks to work after an update, but now in order for them to work I will have to explicitly set the path of all of my shell script commands, resulted in several hours of fixing pipelines.

**Your Environment**
Azure Devops (cloud) with the Ubuntu Agent

**Comment by Cseverance** [comment]
In the meantime, a workaround is to explicitly set the working directory to $(System.DefaultWorkingDirectory) . This is just frustrating because it is pervasive in my release pipelines.

**Comment by hunterwerlla** [comment]
In our next version, "System.DefaultWorkingDirectory" will be the default again

**Comment by hunterwerlla** [comment]
This is fixed as part of today's 1.4.0 release
