### ISSUE TITLE
CFN Change Set Name ValidationError with variables 

### ISSUE THREAD

**Issue by r2690698** [aws/aws-vsts-tools#27]
trying to use a ENV Var to set the Change Set Name and not having much luck, looks like the input is being validated and it fails to meet the constraint because of the $_()  

it should do the evaluation of the string after its been transformed. unless im doing something stupid ( always possible) 

2017-10-11T16:30:25.3834998Z   message: '1 validation error detected: Value \'vsts-$(BUILD_BUILDNUMBER)\' at \'changeSetName\' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*',
2017-10-11T16:30:25.3834998Z   code: 'ValidationError',

**Comment by steveataws** [comment]
I would have expected the environment to have already substituted $ variables before the task retrieves them.  That's what I see in other tasks (for example S3 upload, where my test pipelines refer to the source folder for the upload using $(Build.Repository.LocalPath). 

The variable you are referencing seems to be ok - [this page](https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/build/variables?tabs=batch) shows $(Build.BuildNumber) or $(BUILD_BUILDNUMBER) to be equivalent. Can you try with the alternate name (just to rule out any oddities)?

**Comment by r2690698** [comment]
got it working using $(Release.ReleaseName) that will do for my needs and more importantly the validation is definitely happening after the transform :)
