### ISSUE TITLE
Lambda Tags Not Applied

### ISSUE THREAD

**Issue by StephenRSkinner** [aws/aws-vsts-tools#270]
**Describe the bug**
Setting tags on the Deploy Lambda task does not set the tags on the lambda. I'm working with an existing lambda, so not sure if it's an update issues.

**To reproduce**
1. Add a tag to an existing Deploy Lambda task.
2. Execute a release.

**Expected behavior**
The tag should be applied to the lambda.

**Your Environment**
TFS 2018 On-Premise

**Comment by hunterwerlla** [comment]
I'll see if I can reproduce

**Comment by hunterwerlla** [comment]
It looks like tags are not being added on update, I will fix this

**Comment by hunterwerlla** [comment]
This is now fixed in the 1.5 release
