### ISSUE TITLE
ECR Push task logs the entire docker login command

### ISSUE THREAD

**Issue by ggmaresca** [aws/aws-vsts-tools#272]
**Is your feature request related to a problem? Please describe.**
The Amazon ECR Push task is logging the entire `docker login` command, which includes the authorization token. This allows anyone who has read access to the pipeline the ability to pull and push from ECR from 24 hours.

**Describe the solution you'd like**
The docker login command can not be logged, or the log can obfuscate the token.

**Describe alternatives you've considered**
Using the AWS Shell Script task to replicate the ECR upload task.

**Additional context**
The `docker login` command is occurring at [https://github.com/aws/aws-vsts-tools/blob/master/Tasks/ECRPushImage/TaskOperations.ts#L109](https://github.com/aws/aws-vsts-tools/blob/master/Tasks/ECRPushImage/TaskOperations.ts#L109)

**Comment by hunterwerlla** [comment]
This is now fixed in the 1.5 release, thanks for bringing this to our attention!
