### ISSUE TITLE
S3 Upload - Content-Type set to "application/octet-stream"

### ISSUE THREAD

**Issue by git-jim** [aws/aws-vsts-tools#3]
I'm using the S3 Upload task to push an Angular web site into an S3 bucket during a build.  Every file that ends up in the bucket has its content type set to `application/octet-stream` no matter what the file type is.  I'm not seeing an option to control the metadata - is there something I need to make sure I setup in my VSTS build definition?

**Comment by incarnate** [comment]
By default AWS will set the content type to `application/octet-stream` as you've discovered, for it to be set to anything else it needs to be explicitly declared. The [current version of the upload task](https://github.com/aws/aws-vsts-tools/blob/master/Tasks/S3Upload/helpers/taskOperations.ts#L115) doesn't do that.

One option would be to add some smarts to the task to set the appropriate content type, a task I currently use for S3 has the following:

    let extn = file.split('.').pop();
    let contentType = 'application/octet-stream';
    if (extn == 'html') contentType = "text/html";
    if (extn == 'css') contentType = "text/css";
    if (extn == 'js') contentType = "application/javascript";
    if (extn == 'png' || extn == 'jpg' || extn == 'gif') contentType = "image/" + extn;

    s3.upload({Body: body, ContentType: contentType}).
      send(function(err, data) {
        ....

**Comment by steveataws** [comment]
Adding a bunch of smarts as incarnate@ suggests, and also an explicit ContentType parameter for files not covered by the smarts or when something else is required. I'll update the issue when it's released.

Thanks for the request.

**Comment by giuliov** [comment]
I worked around the issue using the **AWS Tools for Windows PowerShell Script**.
Here is my code

```
param($SourceDir,$BucketName)

$ContentTypes = @{
 "html"="text/html; charset=utf-8";
 "css"="text/css";
 "js"="application/javascript";
 "png"="image/png";
 "jpg"="image/jpeg";
}

if (! $SourceDir.EndsWith("\")) { $SourceDir += "\" }
$noisePrefix=$SourceDir.Replace('\','/').ToLowerInvariant()

Get-ChildItem $SourceDir -File -Recurse | foreach {
	$suffix = [IO.Path]::GetExtension($_.Name).Substring(1)
	$ct = $ContentTypes[$suffix]
	if (!$ct) {
		$ct = "application/octet- stream"
	}

	$key = $_.FullName.Replace('\','/').ToLowerInvariant().Replace($noisePrefix,'')
	
	Write-Host "Uploading $( $_.FullName ) to ${BucketName}:${key}"
	Write-S3Object -File $_.FullName -BucketName $BucketName -Key $key -ContentType $ct -Force
	# MEMO -Metadata @{}
}
```

**Comment by steveataws** [comment]
v1.0.2 has just been published with support for content types. 

The S3Upload task now attempts to auto-determine content type based on file extension, using the same data as the AWS SDK for .NET and AWS Toolkit for Visual Studio. To support custom use cases, we have also added a a new 'Content Type' parameter, listed in the Advanced configuration section, that allows a custom string to be set.  Note that if the task parameter is used, it overrides detection based on file extension.

**Comment by incarnate** [comment]
Looks great, thanks Steve

**Comment by giuliov** [comment]
It works for me also: thanks.
