### ISSUE TITLE
Getting error while running AWS code deploy task in tfs 2015 update4

### ISSUE THREAD

**Issue by samgkz** [aws/aws-vsts-tools#300]
Hi Team, 
I am getting below error in AWS Code deploy task while running intial stage.

I can't able to understand the problem because of no information in log. Please help me to fix this.

9-10-20T18:03:27.2465316Z Starting task: Deploy with CodeDeploy: Agro 2019-10-20T18:03:28.0492435Z Set workingFolder to default: E:\Webagent\tasks\CodeDeployDeployApplication\1.5.0 2019-10-20T18:03:38.8180490Z E:\Webagent\tasks\CodeDeployDeployApplication\1.5.0\CodeDeployDeployApplication.js:13 2019-10-20T18:03:38.8188913Z */Object.defineProperty(t,"__esModule",{value:!0});const i=r(80),a=r(854),s=r(12);t.revisionSourceFromWorkspace="workspace",t.revisionSourceFromS3="s3",t.defaultTimeoutInMins=30,t.buildTaskParameters=function(){const e={awsConnectionParameters:i.buildConnectionParameters(),applicationName:a.getInputRequired("applicationName"),deploymentGroupName:a.getInputRequired("deploymentGroupName"),deploymentRevisionSource:a.getInputRequired("deploymentRevisionSource"),revisionBundle:"",bucketName:a.getInputRequired("bucketName"),bundlePrefix:"",bundleKey:"",description:a.getInputOrEmpty("description"),fileExistsBehavior:s.getInput("fileExistsBehavior",!1),updateOutdatedInstancesOnly:s.getBoolInput("updateOutdatedInstancesOnly",!1),ignoreApplicationStopFailures:s.getBoolInput("ignoreApplicationStopFailures",!1),outputVariable:a.getInputOrEmpty("outputVariable"),timeoutInMins:Number(s.getInput("timeoutInMins",!1))||t.defaultTimeoutInM 2019-10-20T18:03:38.8197336Z SyntaxError: Unexpected token = 2019-10-20T18:03:38.8214182Z at exports.runInThisContext (vm.js:53:16) 2019-10-20T18:03:38.8222605Z at Module._compile (module.js:387:25) 2019-10-20T18:03:38.8231028Z at Object.Module._extensions..js (module.js:422:10) 2019-10-20T18:03:38.8239451Z at Module.load (module.js:357:32) 2019-10-20T18:03:38.8247874Z at Function.Module._load (module.js:314:12) 2019-10-20T18:03:38.8256297Z at Function.Module.runMain (module.js:447:10) 2019-10-20T18:03:38.8264720Z at startup (node.js:146:18) 2019-10-20T18:03:38.8273143Z at node.js:404:3 2019-10-20T18:03:39.1162232Z Finishing task: CodeDeployDeployApplication

**Comment by samgkz** [comment]
![TFS Update4 AWS Code Deploy error](https://user-images.githubusercontent.com/40204117/67265543-95c89600-f4cb-11e9-8104-a1e54fbca308.JPG)

**Comment by samgkz** [comment]
![TFS Update4 AWS Code Deploy error](https://user-images.githubusercontent.com/40204117/67265676-ec35d480-f4cb-11e9-8788-4441c9608e72.JPG)

**Comment by hunterwerlla** [comment]
Hello, 1.5.0 is not supported on TFS 2015, the note in the readme (Note for Team Foundation Server 2015 Users) has the link to the last version supported on TFS 2015, thanks.
