### ISSUE TITLE
Support for sessiontoken in service connection

### ISSUE THREAD

**Issue by EmFl** [aws/aws-vsts-tools#320]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to configure the AWS service connection with temporary credentials (Add support for session token). 

**Describe the solution you'd like**

It would be much simpler if the official AWS endpoint would support token field (with a warning that this is probably not needed in most cases)

**Describe alternatives you've considered**

To achieve this today, I had to create my own extension to define a new type of service connection, and a new build step that takes the values from that custom endpoint and defines them as env variable (AK/SK/Token). Since the scripts handle the session token if it's defined, this works ok. I run the official steps without defining an endpoint so that it uses env variables.
This custom endpoint params are refreshed every X minutes via a lambda function that handles the temp credentials generation. 
This has the benefit for us of never storing long lived tokens in Azure Devops.
It has also the added benefit of not being snapshotted, so we can rerun the same release even if our credentials rotated (which is not the case with build variables)

**Comment by hunterwerlla** [comment]
This is now released as part of 1.6.0
