### ISSUE TITLE
Help needed: Script Path Awspowershell tool

### ISSUE THREAD

**Issue by dairuin** [aws/aws-vsts-tools#324]
hello 
i need help, in my pipeline i need to run a script in powershell to do dome thing on my aws account.. i try to put in the filed script path s3 url for my powershell script . mu build failed with this error: #[error]Invalid file path  A path to a .ps1 file is required

What path needed to insert ??

thanks

**Comment by hunterwerlla** [comment]
Hello, the Powershell script needs to be available on the build machine, a S3 URL will not work. To do what you want here, you can use the S3 pull task to pull down the script before the Powershell stage.
