### ISSUE TITLE
Json Payload Is Not Understood By Lambda From Azure Devops Lambda Invoke Task

### ISSUE THREAD

**Issue by ysnikitin** [aws/aws-vsts-tools#330]
I have a Azure Devops AWS Invoke task for my lambda with a JSON payload, image below:

<img width="748" alt="invoke" src="https://user-images.githubusercontent.com/1461424/75999555-63469500-5ed0-11ea-82b8-6dd8fe027a7f.png">

However, my Lambda (with proper serializers annotations) fails with this error:

> Error converting the Lambda event JSON payload to type MyNameSpace.MyClass Error converting value "{"removeIndexes": true}" to type 'MyNameSpace.MyUtilities.DatabaseSyncRequest'. Path '', line 1, position 27.: JsonSerializerException

Class is this:

```
public class MyClass
{
    public bool RemoveIndexes { get; set; } = false;
    public bool ForceUpdateIndexedColumns { get; set; } = false;
    public IEnumerable<string> EntityNamesToSync { get; set; }
}
```

Invoking it manually with the CLI works fine:

`aws lambda invoke --function-name my-lambda --payload '{ "RemoveIndexes": "true" }' --region 'us-west-2' --profile MYPROFILE response.json`

I noticed in TaskOperations.ts that a `JSON.stringify()` is done and I don't understand why and think this might be the cause of this issue:

https://github.com/aws/aws-vsts-tools/blob/master/Tasks/LambdaInvokeFunction/TaskOperations.ts (line 22)

In Chrome:
`JSON.stringify('{"removeIndexes": true}'); => ""{\"removeIndexes\": true}""`

If I send that payload with the AWS CLI, I get the same error!

`{
    "FunctionError": "Unhandled", 
    "ExecutedVersion": "$LATEST", 
    "StatusCode": 200
}`

I tried escaping, removing braces, spaces, everything in Azure Devops Tasks, but it doesn't work. When the payload is blank its working fine and the default MyClass is used. Can someone provide any guidance on this?

**Comment by hunterwerlla** [comment]
This is definitely in need of cleaning up, instead of JSON.stringify the item needs to be placed in a buffer

**Comment by hunterwerlla** [comment]
Until we fix the issue and do another release, a person with a previous issue similar this put the payload in S3 to work around the issue

**Comment by ysnikitin** [comment]
@hunterwerlla So I can appropriately communicate exceptions and develop a plan, would you have an approximate timeline of how long this could take. If I sent a PR, would that expedite anything?

**Comment by ysnikitin** [comment]
@hunterwerlla thank you for merging this so fast.

**Comment by hunterwerlla** [comment]
This is now released as part of 1.6.0

**Comment by ysnikitin** [comment]
@hunterwerlla thank you very much!

**Comment by hunterwerlla** [comment]
@ysnikitin were you able to verify your use case now works? Thanks

**Comment by ysnikitin** [comment]
@hunterwerlla seems to work. Logs show that our Azure Devops instance using v1.6.0 now.

`020-03-17T02:38:00.1120286Z Task         : AWS Lambda Invoke Function
2020-03-17T02:38:00.1120536Z Description  : Invokes an AWS Lambda function
2020-03-17T02:38:00.1120736Z Version      : 1.6.0
2020-03-17T02:38:00.1120946Z Author       : Amazon Web Services
2020-03-17T02:38:00.1121973Z Help         : Please refer to [AWS Lambda Developer Guide](https://docs.aws.amazon.com/lambda/latest/dg/) for more information on working with AWS Lambda.`

Thanks!
