### ISSUE TITLE
Allow Endpoint Configuration to Use Machine Role instead of Access/Secret Key?

### ISSUE THREAD

**Issue by kellydoesmath** [aws/aws-vsts-tools#34]
Currently, if the TFS agent is deployed inside AWS, an Access Key and Secret key is needed for the commands. Would it be possible to use a Machine Role instead?

**Comment by steveataws** [comment]
We think so and are looking into adding support for instance profile credentials. I don't have an ETA just yet though.

**Comment by JeffRausch** [comment]
Is there any update with this?  We're just getting started using VSTS but this feature would make it easier to manage access and I think it would be considered more secure than having an access key and secret key stored with a third party (Microsoft).

**Comment by steveataws** [comment]
Dev work is complete (or at least I think it is!) and the requirement to set an endpoint and/or region on tasks is now relaxed. If not configured at the task level the tasks will attempt to get credentials and/or region from environment variables or, if the build host is an EC2 instance, from instance metadata allowing credentials to be set using the machine role.

I don't have an exact ETA for release right now (I'm doing some final testing) but hopefully this final phase will be completed quickly and an update posted.

**Comment by steveataws** [comment]
Resolving, update included in the v1.1.0 update released Aug 2nd.
