### ISSUE TITLE
AWS Tools For Powershell Requires Credentials Saved On Server

### ISSUE THREAD

**Issue by alpacamybags118** [aws/aws-vsts-tools#36]
So, I'm not sure if this is intended, but this doesn't match how the other AWS tools work from my experience.

For reference, I am using Version 1.0.12 of the tasks.

When I tried to run a custom powershell block with the AWS Tools For Powershell, it gave me the following error:

`Unable to locate credentials. You can configure credentials by running "aws configure".`

Within the task properties, I am selecting an endpoint with valid credentials that I am using for other AWS tools tasks in the same build process. For example, my previous step in this build is using the AWS Lambda .NET Core Deployment task, and it is able to properly take the credentials from the endpoint.

To get the Powershell task to run successfully, I had to run aws configure on the server that is running the build job and add the credentials directly on the server.

I know this is a slightly different task since I'm running powershell in-line, but I would expect the task to still use the credentials from the selected endpoint. Let me know if you need any additional information to look into this more!

**Comment by steveataws** [comment]
The output message you show actually comes from the AWS CLI, not the AWS Tools for PowerShell (they are different command line tools). It looks as though you are trying to run AWS CLI commands inside a script block supplied to the AWS PowerShell task.

The AWS PowerShell task sets up credentials, but writes them by default to the secured credential store used by our .NET SDK and tools, which isn't accessible by the AWS CLI - it will look for credentials in the shared credentials file. It is possible for the AWS PowerShell cmdlets to write credentials to the shared credentials file but that's not a scenario we currently support in the task.

Can you give me some idea of the AWS CLI commands you are trying to run in the AWS PowerShell task? Both CLIs target the same set of services so you shouldn't necessarily need to mix them. Given the CLI commands I can likely get you the corresponding PowerShell cmdlets (or you can do this yourself on your local workstation if you have our PowerShell modules installed) using the cmdlet

Get-AWSCmdletName - AwsCliCommand "command"

For example 'Get-AWSCmdletName -AwsCliCommand "ec2 describe-instances"' will return the name Get-EC2Instance.

**Comment by alpacamybags118** [comment]
Oh, that makes sense. Thanks for explaining! So, I'm calling `aws lambda publish-version`. Based on the documentation, it looks like I would need to use `Publish-LMVersion`. I think I should be able to figure it out from here. Thanks again for your help!

**Comment by steveataws** [comment]
No worries. I'll close the issue, if you hit problems feel free to reopen.
