### ISSUE TITLE
AWS Lambda .NET Core Deployment ignores Function Handler

### ISSUE THREAD

**Issue by HWouters** [aws/aws-vsts-tools#37]
The AWS Lambda .NET Core Deployment task ignores the configured Function Handler parameter.

Work around: in 'Additional Lambda Tools Command Line Arguments' specify the `--function-handler` argument

**Comment by steveataws** [comment]
Do you have a defaults file for the tools in the project folder (aws-lambda-tools-defaults.json)? The function handler should be read from that file by the dotnet cli Lambda extension, if the relevant property is set in the file. You should only need the command line argument if you want to override the handler.

Are you seeing a case where the handler name is present in the file but isn't being read by the tools?

**Comment by HWouters** [comment]
Thanks, I wasn't using the aws-lambda-tools-defaults.json. Now I do and I don't need the command line argument anymore. But still it's a bit strange you can configure the Function Handler parameter, which is never used. I would expect it overrides the configured handler.

**Comment by steveataws** [comment]
It should, sounds like we have a bug in there somewhere that I'll take a look at.

**Comment by steveataws** [comment]
HWouters@, v1.0.13 is now released with a fix for this. Let me know if it works OK for you, then I'll close the issue.

**Comment by HWouters** [comment]
@steveataws. That's the fix, it works now. Thank you!
