### ISSUE TITLE
AWS CLI is not installed on this machine

### ISSUE THREAD

**Issue by giuliov** [aws/aws-vsts-tools#4]
On Hosted agents AWS CLI is not installed. This should be noted in the docs.

**Comment by steveataws** [comment]
The [task reference page](http://docs.aws.amazon.com/vsts/latest/userguide/aws-cli.html) notes that the CLI must be pre-installed,  but not the task help itself when inside the VSTS environment. I'll get that updated in the next release.

Thanks for reporting.

**Comment by steveataws** [comment]
v1.0.2 just released with changes to note the install requirements in the tooltip for the task. The tooltip contains a link to the AWS CLI install instructions in the AWS documentation (https://docs.aws.amazon.com/cli/latest/userguide/installing.html)

**Comment by JulioIzquierdo** [comment]
I have installed the AWS CLI using various methods and I'm still receiving the error: "##[error]AWS CLI is not installed on this machine."
I've used PIP, MSI and finally the EXE file to install the CLI.  I've used it as an Agent then as a Group Deployment but to no avail.  For each installation, I've confirmed that AWS CLI was installed by using aws --version.
Any thoughts or suggestions?  I would greatly appreciate it.

**Comment by JeffRausch** [comment]
@JulioIzquierdo  I installed it recently on a machine and what worked for me was restarting the machine after installation, have you tried that?  A restart of the agent service might also work.  
If you're able to log into the machine are you able to access the CLI from a command prompt if you're logged into it?  That would at least tell you that the CLI is in fact installed correctly.

**Comment by JulioIzquierdo** [comment]
I'll try restarting the machine.

In all instances, i was logged into the machine to install AWS CLI using the various install methods and I confirmed each time that it was available by using the cmd aws --version. Just not sure why the task extension says it cannot find it.



-------- Original message --------

**Comment by JulioIzquierdo** [comment]
Yep, that did it. 👍 
Thank you @JeffRausch
