### ISSUE TITLE
AWS Elastic Beanstalk Version Label

### ISSUE THREAD

**Issue by radupintilie** [aws/aws-vsts-tools#40]
Hi!
We're using TFS to deploy a PHP app to AWS Elastic Beanstalk and everything works great but we're missing the functionality to set the Version Label.

![tfs](https://user-images.githubusercontent.com/2639347/33124460-bb6d1128-cf85-11e7-9dad-25beacb88da3.png)

![aws](https://user-images.githubusercontent.com/2639347/33124459-bb4c6432-cf85-11e7-9f2a-6ade2fe1cebe.png)

Thanks,
Radu

**Comment by steveataws** [comment]
Consider it done :-)

We are planning on releasing an update to the tools next week at our AWS re:Invent conference. Does it cause you any extra issues if I hold onto the change until then?

**Comment by radupintilie** [comment]
Hi Steve,

Thanks for the fast reply. Next week sounds great for this feature.
