### ISSUE TITLE
Template body size in a request to large.

### ISSUE THREAD

**Issue by r2690698** [aws/aws-vsts-tools#41]
Hello, 

ITs well know there is a template body size limit of 51,200 bytes ( listed in the limits doc), this is VERY limiting. 

The approach used normally is to upload to S3 and use that as a reference. can we have this process build in too ?

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html

**Comment by steveataws** [comment]
Sure, we can do that. It should be pretty simple, hopefully I can work it into the planned update next week at our AWS re:Invent conference (but no promises!).

**Comment by r2690698** [comment]
ah thanks very much, will solve a number of issues :) 

you guys are doing a brill job +!

**Comment by steveataws** [comment]
v1.0.14 is now released with new options for controlling the location of the template file (local file, the default, or a url or bucket/key combination).

HTH

**Comment by steveataws** [comment]
Resolving issue now update released.
