### ISSUE TITLE
credentials file always open

### ISSUE THREAD

**Issue by Bluestreak2k5** [aws/aws-vsts-tools#43]
I have Visual Studio working with AWS Toolkit using an AWS Role credientials.

I have a batch process that grabs credientials from a machine every hour and stores in the default location to run commands. This allows commands etc to always have a fresh set of credientials without creating an IAM user.

However, AWS Toolkit throws a blocker in this because it keeps the file open forever as long as visual studio is open. This prevents me from writing the new credientials on a regular basis.

Can you please make the toolkit load the credientials every few minutes or so instead of keeping the file open the entire time.

**Comment by steveataws** [comment]
Hi there,

This repo is for the tools for VSTS, not the toolkit for Visual Studio (the VSTS tools don't use or access the credential profile file).  The same dev team works on both tools.

I know the toolkit watches the credential files for changes, but I'm not aware that it is keeping them open. In this case, I'm assuming you are trying to write to the ini-format credential file shared with other sdk's, not the toolkit's private credential file (where the credentials are encrypted). It might be an issue in the underlying sdk, so Can I ask you to open a request on the team's [sdk](https://github.com/aws/aws-sdk-net) repo and we'll take a look?

**Comment by steveataws** [comment]
Closing issue in favor of [aws/aws-sdk-net/issues/806](https://github.com/aws/aws-sdk-net/issues/806).
