### ISSUE TITLE
How to upload encrypted objects using s3 upload task in VSTS.

### ISSUE THREAD

**Issue by akkipuneet** [aws/aws-vsts-tools#47]
Through AWS CLI we can encrypt object with below command 
aws s3 cp .\abc.txt s3://mybucket/ --sse AES256

But how to do the same from S3 upload task in VSTS . I am not able to find anywhere over the internet

**Comment by steveataws** [comment]
The S3 Upload task doesn't currently support the various encryption options, but we can add it. In the meantime, you can make use of either of the AWS CLI or AWS PowerShell Tools tasks to script out a workaround.

**Comment by akkipuneet** [comment]
Thank you Steve for the information . Can you please share , when we can expect encryption support for S3 upload task .

**Comment by steveataws** [comment]
I can't give a specific date but usually these enhancements take a few days to a week or two depending on other workloads. We are of course heading into holiday season but I'll see what I can do to get this out before then.

**Comment by steveataws** [comment]
Encryption support has now been added and released as v1.0.15. Resolving feature request, if you exhibit any issues or concerns feel free to reopen.
