### ISSUE TITLE
feature request - SSM Param Store Support 

### ISSUE THREAD

**Issue by r2690698** [aws/aws-vsts-tools#48]
Hello, 

As a DevOps Engineer i would love the ability to manage SSM Param Store values as a task in the VSTS pipeline out of the box. 

Each Task should be able to support multiple parameters ( infinite add list ), a bit like this. 

Region  [_________] 
Credential [_________] 
KMS KeyID [_________] 

Name [_________] Value  [_________]  Type  [_________]  [-]
Name [_________] Value  [_________]  Type  [_________]  [-]
Name [_________] Value  [_________]  Type  [_________]  [+] [-]

**Comment by steveataws** [comment]
Are you thinking in terms of managing these at the task configuration level, or in some form of dashboard widget?

We've looked at grid usage when defining tasks and haven't seen anything we really like or could easily adapt yet. Dashboard widgets is an unexplored area we're thinking of taking a peek at.

**Comment by steveataws** [comment]
The new 1.1.0 release we shipped today has a new task enabling create or update of parameters in the store. Does this help any?

https://aws.amazon.com/blogs/developer/updates-to-the-aws-tools-for-visual-studio-team-services/

**Comment by hunterwerlla** [comment]
Closing as this is now supported
