### ISSUE TITLE
 Help with glob minimatch patterns

### ISSUE THREAD

**Issue by tumbleweedbill** [aws/aws-vsts-tools#49]
The Glob minimatch patterns that we are entering in the task are not correctly matching the files to be copied to s3.  In the first task, we want to match all extensionless files in both the root and any subdirectories and we have tried "!**/*.*" which should appear to work (tested on http://www.globtester.com/ ).  In the second task we are trying to match any file with a distinct list of extensions in both the root and any subdirectory.  We have tried "**/*.{css,js,png,ico,xml,gif}" which also should work but does not.  How can we debug this or is there something we are missing?

**Comment by steveataws** [comment]
The tasks use the built-in match helper on the VSTS task library's [task](https://github.com/Microsoft/vsts-task-lib/blob/a4be3729c2416c90fc6876902eb60e5e062d7c63/node/task.ts#L1174) type, which I think is based on minimatch. 

I guess it's possible it needs a different syntax, or maybe isn't supported - like you I'll have to experiment to figure it out and if we can't get it to work, raise a question on the forums for the task library to see if Microsoft staff have any thoughts.

**Comment by hunterwerlla** [comment]
Looking at their master branch, it seems like their matching algorithm has been updated to support this
