### ISSUE TITLE
S3 Upload - Bucket [BUCKET_NAME] does not exist or you do not have access

### ISSUE THREAD

**Issue by jsancho** [aws/aws-vsts-tools#5]
That's the error I get when using the S3 Upload task to send an artifact to an already existing bucket.

I'm trying this on a Hosted Linux VSTS agent.

I'm confident that my IAM policies are fine, since I can upload the file without issues from my local box like so
`aws configure set aws_access_key_id *********`
`aws configure set aws_secret_access_key ********`
`aws s3 cp build_artifact.tgz s3://[BUCKET_NAME]/build_artifact.tgz --region eu-west-1`

At the moment I'm only granting s3:PutObject permission, but I've also tried with s3:* just in case read access was required.

The rest of my configuration is pretty close to the one on the screenshot in your README.

Full output below.
(Please note that I have obscured the name of the bucket to avoid disclosing it publicly)

`2017-08-19T18:15:27.2379850Z ##[section]Starting: S3 Upload: [BUCKET_NAME] 
2017-08-19T18:15:27.2463490Z ==============================================================================
2017-08-19T18:15:27.2476820Z Task         : AWS S3 Upload
2017-08-19T18:15:27.2489660Z Description  : Upload file and folder content to an Amazon Simple Storage Service (S3) Bucket
2017-08-19T18:15:27.2503150Z Version      : 1.0.2
2017-08-19T18:15:27.2516010Z Author       : Amazon Web Services
2017-08-19T18:15:27.2529530Z Help         : Please refer to [Working with Amazon S3 Buckets](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html) for more information on working with Amazon S3.
2017-08-19T18:15:27.2544250Z ==============================================================================
2017-08-19T18:15:27.5998270Z 18596219-1165-4cd7-b448-95ea29bbe30d exists true
2017-08-19T18:15:27.7965780Z ##[error]Error: Bucket [BUCKET_NAME] does not exist or you do not have access. Auto-create option not set, cannot continue.
2017-08-19T18:15:27.8090710Z ##[section]Finishing: S3 Upload: [BUCKET_NAME] 
`

Thanks for helping out

**Comment by jsancho** [comment]
I've been doing some further testing today. 
With a fresh AWS account even, and I can reproduce the issue with a minimal subset of tasks.

The upload does actually work fine I use the root AWS account.
However, the upload fails with the "bucket name does not exist or you do not have access..." whenever I use an account other than the root one.

This limited account has the following policy attached.
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1503241903611",
            "Action": "s3:*",
            "Effect": "Allow",
            "Resource": "arn:aws:s3:::fake-bucket-name/*"
        }
    ]
}`

I have also tried using a bucket policy and assigning the principal, but that's made no difference.

As with my main organisations' account, I can use "aws s3 cp" with the limited account key and secret.

**Comment by steveataws** [comment]
Thanks for digging into this. I've repro'd with the policy shown and am investigating further.

The task performs a [HEAD](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketHEAD.html) operation before running, which, according to the linked S3 documentation on [permissions](http://docs.aws.amazon.com/AmazonS3/latest/dev/using-with-s3-actions.html#using-with-s3-actions-related-to-buckets) should need more permissions than your policy shows. However, even after adding ListBucket and GetBucketLocation permissions I didn't see a change in behavior. The CLI's S3 cp command presumably doesn't do a HEAD request to test bucket existence, so it works fine.

It's possible I missed something in the permissions so am continuing to look. If that doesn't yield any results, maybe there is a bug in the underlying AWS SDK for Node.js, so I'll query with that team to see if they have any ideas too.

**Comment by steveataws** [comment]
Following the documentation [here](http://docs.aws.amazon.com/AmazonS3/latest/dev/using-with-s3-actions.html), this is the policy I crafted for a limited account that allowed upload (only) to my test bucket, 'steve-limited' -

`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "LetMyLimitedAccountSeeTheBucket",
            "Effect": "Allow",
            "Action": [
                "s3:GetBucketLocation",
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        },
        {
            "Sid": "LetMyLimitedAccountUploadToTheBucket",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::steve-limited",
                "arn:aws:s3:::steve-limited/*"
            ]
        }
    ]
}`

Let me know if this works for you too? Using the information on the linked page, you might want to customize further.

Thanks for the comments too!

**Comment by jsancho** [comment]
Wow, that's what it is indeed.

If I narrow it down to a single policy, with the minimum set of permissions, I come to the following
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "LetMeSeeThisBucketSoICanWriteToIt",
            "Action": [
                "s3:GetBucketLocation",
                "s3:ListBucket",
                "s3:PutObject"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::bucket-name-here"
            ]
        }
    ]
}`

I can even create subfolders without using the "resource" that has a wildcard in its path. 
Matter of fact is that's part of what the problem was, since I was using the wildcard version only, and s3 was not playing ball.

Thanks!

**Comment by jsancho** [comment]
I've just deleted an earlier comment that wasn't that accurate. 
In order to avoid confusion, I'll summarising it all here.

When I narrow down all the permissions that are required for the upload. 
I end up with the following:

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "LetMeSeeTheBucketSoICanUploadToIt",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketLocation",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::bucket-name"
            ]
        }
    ]
}

**With this configuration I can even create subfolders and overwrite files in the bucket.**

The takeaways are:
- All 3 actions above are required 
- The bucket needs to be specified as the plain root path, the version with the wildcard at the end "/*" is not necessary 

Thanks so much for looking into this and pointing me in the right direction 
top work! 👍

**Comment by steveataws** [comment]
Great to hear you are up and running. Did you also manage to confirm the AWS CLI task worked when you had this policy in place?

**Comment by jsancho** [comment]
Afraid that I've not managed to get the CLI task to work, I'll add the comments in that issue

**Comment by steveataws** [comment]
Ok. I'll close this issue and we can move over to the CLI one.
