### ISSUE TITLE
S3 Upload - Setting Cache Control

### ISSUE THREAD

**Issue by aro1976** [aws/aws-vsts-tools#50]
These days we are building several single page web applications, it would be very important if vsts-tools had option to set cache control settings, like:
`
--cache-control 'max-age=2592000, public'
`

**Comment by steveataws** [comment]
Ok sure, we'll see what we can do. I can't give an ETA at this time but if it's super urgent, we'd also be happy to take a pull request.

**Comment by aro1976** [comment]
I was thinking about creating a parameter with a list of glob expressions plus a separator and cache configuration like:
*.js = 84000, public
*.html = 3600, public
If you agree with this aproach I'll try this tomorrow.

**Comment by steveataws** [comment]
Sure, that seems reasonable and fits in with other tasks where we've worked around a lack of grid control in task definitions by using a multiline text field with separators (eg for tags).

**Comment by aro1976** [comment]
@steveataws do you have any packaging instructions for this extension?

I tried `npm run build` and `npm run package` but it seems to be failing while trying to resolve sdkutils, I attached the console [package.log](https://github.com/aws/aws-vsts-tools/files/1609108/package.log).

**OS**
MacOS: 10.13.2 

**Tool Versions:**
node: v8.9.3
npm: 5.5.1
tsc: 2.6.2
tfx: 0.5.3
visual studio code: 1.19.1

**Comment by steveataws** [comment]
The way I build and test is to open a shell onto the root folder, and then run the command

gulp package --publisherid _publisher_ --release

This will create a private .vsix file in the _package folder, that I then install into my TFS installs. For VSTS, I upload it to my _publisher_ account and share it with my test account.

**Comment by steveataws** [comment]
aro1976@, did you make any progress on this update? Anything I can do to help?

**Comment by aro1976** [comment]
Actually I think it is almost finished, but I didn't figure out what's going wrong during packaging.
[![screen-2018-01-13 22-05-46](https://user-images.githubusercontent.com/420849/34916086-09527ee8-f919-11e7-9115-23858dd64451.png)
](url)

**Comment by steveataws** [comment]
Hmm, that's an odd message I've not seen before. Not sure if it will help but from our build server, this is the sequence of npm commands run to get us to the vsix package:

node make.js clean
node make.js build  --release 
node make.js package --publisher your-pubid-here --release

On my dev workstation, as noted earlier, I have gulp installed and simply run a gulp command for simplicity.

**Comment by aro1976** [comment]
I checked out this repo in a linux machine but still having the same error, I'm afraid there might have a problem with node or npm versions. Would you please tell me the versions you are using? (npm, node, tsc, and tfx)

**Comment by steveataws** [comment]
The tool chain on my Windows 10 laptop, where I do most of the work, has the following versions:

node: 6.11.0
npm: 3.10.10
gulp: 3.9.1
tsc: 1.0.3.0
tfx: 0.4.10

On my MacBook where I occasionally poke around with the tools I'm seeing these versions:

node: 6.12.2
npm: 3.10.10
gulp: 3.9.1
tsc: 2.6.2
tfx: 0.5.3

Not sure why the tsc version on my Windows box is so 'low', I generally dev+build inside vscode so maybe it's picking up a later version that way. Either way, on both machines I can build and package without issue,

**Comment by steveataws** [comment]
@aro1976, if you're still blocked do you want to try pushing your branch to the repo and I'll run a build of the branch on my systems to see what results I get?

**Comment by dmarjoram** [comment]
Could also do with this being implemented for our SPA release process.

**Comment by hunterwerlla** [comment]
This is now available in the 1.5 release
