### ISSUE TITLE
There is no way to run a custom shell script with AWS credentials

### ISSUE THREAD

**Issue by lestephane** [aws/aws-vsts-tools#54]
Motivation: I need to run a hashicorp packer command that makes use of the aws-ebs builder from a private linux agent, using an aws endpoint configured in vsts. 

I've tried to use an AWS Powershell Script task, which does not work, since that task is only available for Windows agents (until Powershell.Core support is added, see #53).

I then looked at the AWS Cli task, which does not work, because that task only supports

`aws <command> <subcommand> `

The big gap in the AWS Tools for Team Services, is (i think) a task like

`AWS Shell Script (Run a shell script using bash with aws credentials)`

Which would take either a script file name or an inline script.

As a workaround for now, I could configure the aws credentials in the private linux agent statically, and mark that agent with a capability, and use the `Shell Script` task. But that does not feel right, as the agent might be configured by mistake to access a completely different account.

I looked at the source code, and must admit, i don't have enough knowledge of node / typescript / vsts-extensions to contribute a PR. 

Thoughts?

**Comment by cameronattard** [comment]
+1 for this approach, it's consistent with how Microsoft provide an 'Azure PowerShell script' task.

**Comment by steveataws** [comment]
I like the idea, I'll see what the team can do.

**Comment by samattridge** [comment]
Any news on whether this is likely to be done @steveataws? This would be a really good enabler for me and my team.

**Comment by steveataws** [comment]
It's still in the backlog for consideration but hasn't received any attention yet, as we've been focused on updating credentials and region settings to be more flexible. That work is coming to an end so I'll bump this up the list, maybe we can sneak something in before release :-)

**Comment by samattridge** [comment]
@steveataws That was be fantastic, thank you.  Fingers crossed you get time!  Any idea when the release can be expected?  The credentials and region settings flexibility would also be great.

**Comment by steveataws** [comment]
I can't give an exact ETA but we hope to release the credential changes in July. That gives us some time to consider what to do about shell scripts too :-)

**Comment by samattridge** [comment]
Exciting stuff @steveataws!  Thanks for the update.

**Comment by steveataws** [comment]
Resolving,  included in v1.1.0 released Aug 2nd.

**Comment by samattridge** [comment]
This is great @steveataws!  Thanks so much for this.
