### ISSUE TITLE
Lambda .NET Core Deployment for netcoreapp2.0

### ISSUE THREAD

**Issue by ianByrne** [aws/aws-vsts-tools#56]
With [netcoreapp2.0 functionality recently announced for AWS Lambda](https://aws.amazon.com/blogs/developer/aws-lambda-net-core-2-0-support-released/), do I need to do anything special in my VSTS build task to make use of it? I am receiving the following errors after changing the TargetFramework to 2.0 and attempting a build:

> 2018-01-22T21:39:07.1381607Z Beginning Lambda Deployment
> 2018-01-22T21:39:07.1651518Z Path to tool: C:\Program Files\dotnet\dotnet.exe
> 2018-01-22T21:39:07.1679934Z [command]"C:\Program Files\dotnet\dotnet.exe" lambda deploy-function --disable-interactive true --region us-east-1 -fn FunctionName -fh FunctionName::FunctionName.Function::FunctionHandler --function-role arn:aws:iam::ID:role/Role --function-memory-size 256 --function-timeout 300
> 2018-01-22T21:39:21.9510247Z Executing publish command
> 2018-01-22T21:39:22.0504026Z ... invoking 'dotnet publish', working folder **'d:\a\1\s\FunctionName\bin\Release\netcoreapp1.0\publish'**
> 2018-01-22T21:39:23.7069702Z ... publish: Microsoft (R) Build Engine version 15.4.8.50001 for .NET Core
> 2018-01-22T21:39:23.7070345Z ... publish: Copyright (C) Microsoft Corporation. All rights reserved.
> 2018-01-22T21:39:24.1988596Z ... publish: C:\Program Files\dotnet\sdk\2.0.3\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(165,5): error : Assets file 'd:\a\1\s\FunctionName\obj\project.assets.json' doesn't have a target for '.NETCoreApp,Version=v1.0'. **Ensure that restore has run and that you have included 'netcoreapp1.0' in the TargetFrameworks for your project.** [d:\a\1\s\FunctionName\FunctionName.csproj]
> 2018-01-22T21:39:24.3386621Z ##[error]Error: C:\Program Files\dotnet\dotnet.exe failed with return code: 4294967295

Thanks

**Comment by normj** [comment]
Make sure the version of `Amazon.Lambda.Tools` referenced in your project is version `2,0.1`. Also check in your `aws-lambda-tools-defaults.json` file and make sure the `framework property says `netcoreapp2.0` and `function-runtime` is set to `dotnetcore2.0`.

**Comment by ianByrne** [comment]
That did the trick! Many thanks
