### ISSUE TITLE
feature request - Cloudformation AWS::CloudWatch::Alarm Rollback Trigger 

### ISSUE THREAD

**Issue by r2690698** [aws/aws-vsts-tools#59]
Cloudformation now supports rollback triggers. can we have the supported added into the Cloudformation Task ?  

Monitoring Time
and a list of triggers

AWS::CloudWatch::Alarm
ARN

**Comment by steveataws** [comment]
I've just released v1.0.18 which contains support for configuring rollback triggers in the task. Let me know if it works for you and we can close the issue.

Thanks for the request!

**Comment by steveataws** [comment]
Resolving as this has now been released and available for a few days.
