### ISSUE TITLE
AWS CLI Task - error when using "s3 cp" to upload a file

### ISSUE THREAD

**Issue by jsancho** [aws/aws-vsts-tools#6]
After troubleshooting my report on issue #5 I tried to use the AWS CLI to accomplish the same objective.
Uploading an artifact to an S3 bucket from VSTS.

This is also on a Hosted Linux agent.
The upload works as expected when I try to upload the file by manually executing "s3 cp" in the cli.

To be able to run the cli on a hosted agent, I installed the official ubuntu package via apt-get.
The installed version for "awscli" is 1.11.13-1ubuntu1~16.04.0

The error output leads me to believe that there might be an issue with the string concatenation for the "configure set aws_secret_access_key" command. 
As you can see in the log below the "aws_access_key_id" part is repeated from the previous command, and it looks like it doesn't parse correctly.

`2017-08-19T20:31:27.4213130Z ##[section]Starting: AWS CLI: copy artifact to bucket
2017-08-19T20:31:27.4285300Z ==============================================================================
2017-08-19T20:31:27.4300490Z Task         : AWS CLI
2017-08-19T20:31:27.4315920Z Description  : Run an AWS CLI command
2017-08-19T20:31:27.4330900Z Version      : 1.0.2
2017-08-19T20:31:27.4346380Z Author       : Amazon Web Services
2017-08-19T20:31:27.4365750Z Help         : The AWS Command Line Interface (CLI) is a unified tool to manage your AWS services. With just one tool to download and configure, you can control multiple AWS services from the command line and automate them through scripts. You must have the AWS CLI installed to use this task. See http://docs.aws.amazon.com/cli/latest/userguide/installing.html for more details.
2017-08-19T20:31:27.4382400Z ==============================================================================
2017-08-19T20:31:27.7578150Z 4604ae4d-7b67-42ae-bb99-59837d6e43ce exists true
2017-08-19T20:31:27.7816220Z [command]/usr/bin/aws configure set aws_access_key_id ********
2017-08-19T20:31:28.6579480Z [command]/usr/bin/aws configure set aws_access_key_id ******** configure set aws_secret_access_key ********
2017-08-19T20:31:28.9931390Z 
2017-08-19T20:31:28.9950290Z Unknown options: configure,set,aws_secret_access_key,********
2017-08-19T20:31:29.0566510Z ##[error]/usr/bin/aws failed with return code: 255
2017-08-19T20:31:29.1260640Z ##[section]Finishing: AWS CLI: copy artifact to bucket
`

Here is a screenshot of my task configuration. 
Note that I've masked the name of the bucket.
![aws_issue](https://user-images.githubusercontent.com/1547884/29490524-fa6e831e-8536-11e7-848c-5d82c34a1b9c.png)

**Comment by steveataws** [comment]
Wondering if this issue was in fact a red herring and the true cause was the upload failure (looking at the last line of output). I've attached a policy to the other issue that allowed upload for a limited user account, would you mind retrying with that to see if the cp command now works? Thanks.

**Comment by jsancho** [comment]
On this case it doesn't seem to be a matter of permissions, because I can't even upload with a policy as heavy-duty as this one

```javascript
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1498683497000",
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::bucket-name",
                "arn:aws:s3:::bucket-name/*",
                "arn:aws:s3:::*"
            ]
        }
    ]
}
```
The error is different as well.
If you look at the formatted output the "configure set aws_access_key_id" seems to issued twice.
Then the error looks more like it's the cli complaining about the parameters themselves, not that the query itself failed 

```
2017-08-22T20:42:50.1716410Z [command]/usr/bin/aws configure set aws_access_key_id ********
2017-08-22T20:42:51.0706980Z [command]/usr/bin/aws configure set aws_access_key_id ******** configure set aws_secret_access_key ********
2017-08-22T20:42:51.3737990Z 
2017-08-22T20:42:51.3755150Z Unknown options: configure,set,aws_secret_access_key,********
```

**Comment by steveataws** [comment]
I had wondered about that, but in reviewing the task didn't see any obvious signs of duplication. Taking another look.

**Comment by jsancho** [comment]
I know what you mean, I've been looking at TaskOperations.ts and it all seems fine to me.

I've just run this command on my local box
`aws configure set aws_access_key_id AAAAAAAAAAAAA aws configure set aws_secret_access_key SSSSSSSSSSSSSSSS`

and the error is exactly the same
`Unknown options: aws,configure,set,aws_secret_access_key,SSSSSSSSSSSSSSSS`

**Comment by jsancho** [comment]
The only thing I can think of is that maybe the vsts tool runner is not liking the spacing between configure and set?

instead of
```
awsCliTool.line('configure set aws_access_key_id');
```
use
```
awsCliTool.line('"configure set" aws_access_key_id');
```
https://github.com/Microsoft/vsts-task-lib/blob/master/node/docs/vsts-task-lib.md#toolrunnertoolrunnerline-

This could be nonsense though... difficult to tell without a debugger :/

**Comment by steveataws** [comment]
Debugging tasks can be somewhat tricky. I found a problem in the use of await on the task runner, looking at it now and hope to have a fixed out soon.

**Comment by steveataws** [comment]
v1.0.3 is now released that hopefully resolves your problem. Give it a try and let us know :-)

**Comment by jsancho** [comment]
That's definitely fixed the way that the credentials are passed, thumbs up for that.

However, there seems to be an issue with the way that the "options and parameters" field is parsed.

For example, I have tried with 2 flavour of s3 commands

## aws s3api put-object
![screen shot 2017-08-23 at 18 34 56](https://user-images.githubusercontent.com/1547884/29629742-ca284da4-8831-11e7-830c-156a44d958a2.png)
Output
```bash
/usr/bin/aws configure set aws_access_key_id ********
/usr/bin/aws configure set aws_secret_access_key ********
/usr/bin/aws configure set default.region eu-west-1
/usr/bin/aws s3api put-object --bucket bucket-name --key sources.tgz --body /opt/vsts/work/1/a/sources.tgz
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:
  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: the following arguments are required: --bucket, --key
/usr/bin/aws failed with return code: 2
```

## aws s3 cp
![screen shot 2017-08-23 at 18 42 07](https://user-images.githubusercontent.com/1547884/29630026-cf6de728-8832-11e7-98c8-472d7676f6e5.png)

```bash
/usr/bin/aws configure set aws_access_key_id ********
/usr/bin/aws configure set aws_secret_access_key ********
/usr/bin/aws configure set default.region eu-west-1
/usr/bin/aws s3 cp /opt/vsts/work/1/a/sources.tgz s3://bucket-name/sources.tgz --region=eu-west-1
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:
  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: the following arguments are required: paths
/usr/bin/aws failed with return code: 2
```
The odd thing is that the resulting commands in the output are printed just like they show on my local terminal.
It's just that it seems that they are not being received by the cli tool.

**Comment by steveataws** [comment]
The arg() call we use to add these to the tool runner is documented as accepting a string or string[], with the actual options parameter getting passed back to the task as a string. The task itself does no manipulation of them. It's possible arg() is interfering somehow, let me see what I can find.

**Comment by steveataws** [comment]
arg() is the culprit. Switching to use line() to feed the arguments allows your example to work. I'll spin up a new build now and release shortly.

**Comment by steveataws** [comment]
v1.0.4 is now released. Fingers crossed :-)

**Comment by jsancho** [comment]
and now we're cooking with gas! 🔥 
Amazing, all working on the first go.

Not to sound too greedy, because the CLI plugin gives me an entry point to anything I need in AWS...
But can I just ask if are there any plans to support Opsworks in the future? ;)

Thanks so much for all the hard work

**Comment by steveataws** [comment]
Right now we're evaluating feedback to see what functionality requests come in. So that's a +1 for OpsWorks then :-)

Good to hear you're up and running, and thanks for the feedback!

**Comment by fulghum** [comment]
We're also happy to take pull requests for new tasks. ;-)  Would probably be good to discuss the initial idea/scope on an issue before getting too far along to make sure everybody is on the same page.
