### ISSUE TITLE
Throttling: Rate Exceeded

### ISSUE THREAD

**Issue by systemsymbiosis** [aws/aws-vsts-tools#62]
I am observing the following error that is causing a VSTS Build and Deploy to ElasticBeanstalk to fail

Throttling: Rate exceeded

The log output looks like the following.

```

******************************************************************************
Starting: Deploy to Elastic Beanstalk: dev-1
******************************************************************************
==============================================================================
Task         : AWS Elastic Beanstalk Deploy Application
Description  : Deploys an application to Amazon EC2 instance(s) using AWS Elastic Beanstalk
Version      : 1.0.19
Author       : Amazon Web Services
Help         : Please refer to [AWS Elastic Beanstalk User Guide](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/Welcome.html) for more details on deploying applications with AWS Elastic Beanstalk.
==============================================================================
effb8445-24e1-4f75-b722-435babccdbde exists true
Deployment type set to aspnet
Determine S3 bucket elasticbeanstalk-eu-west-1-xxxxxxxxxxx to store application bundle
Uplo********ng application bundle D:\a\1\a\WebApp.zip to object dev-1/dev-v1/WebApp-v-cf519445591b969eb045-11842.zip in bucket elasticbeanstalk-eu-west-1-xxxxxxxxxx
Application upload completed successfully
Created application version: v-cf519445591b969eb045-11842
Started updating environment to version: v-cf519445591b969eb045-11842
Waiting for deployment to complete
Events from Elastic Beanstalk:
Fri Feb 09 2018 09:24:50 GMT+0000 (Coordinated Universal Time)   INFO   Environment update is starting.
Throttling: Rate exceeded
******************************************************************************
Finishing: Deploy to Elastic Beanstalk: dev-1
******************************************************************************

```

What could be causing this issue? Should I contact AWS Support or is it an issue related to my use of the ElasticBeanstalk VSTS Task?

Any help is most appreciated!

**Comment by steveataws** [comment]
The code to sit in a wait loop printing out events is unchanged from the very first release so I'm unsure why you would suddenly start to be seeing throttling errors. In the last release we did update the version of the AWS SDK for Node.js we use, but it _should_ be performing backoff and retries in throttling scenarios the same as before. I'll check with the owning team to see if there are any known changes in this area.

The loop sleeps for 5 seconds between each iteration so this should be more than enough time (and as I said, hasn't been changed). Are you still experiencing the problem? I'm wondering if the service was experiencing an issue and started throttling more aggressively leading to the built-in backoff and retry events in the sdk becoming exhausted.

**Comment by systemsymbiosis** [comment]
Thanks for your reply. I have tried again today and I do not observe the issue. I may have been hammering my account this week due to lots of testing. I'll keep an eye and report here if I observe the problem again. It could well have been transient.

**Comment by systemsymbiosis** [comment]
Great thanks. We can close this.

**Comment by systemsymbiosis** [comment]
I have been observing this issue many times across many projects in recent weeks. Deployments/Releases in VSTS show as failing due to throttling limits even although ultimately the deployment succeeds it is still reported as failed in VSTS. I have opened a support request with AWS asking for the account throttling limit to be increase. I will report the outcome here. If you have any ideas to contribute in the meantime they will be most appreciated. Many thanks!

**Comment by systemsymbiosis** [comment]
We are conducting further troubleshooting AWS support have got back to me once more with the following reply.

> Thank you for your patience. I have heard back from the service team. 
> 
> It looks like the SDK is likely being throttled on the DescribeEnvironments and/or DescribeEvents API calls. These are called by the SDK every five seconds after UpdateEnvironment is executed so that the SDK can poll for the current status of the deployment: 
> 
> Please look at the code here:
> https://github.com/aws/aws-vsts-tools/blob/master/Tasks/BeanstalkDeployApplication/helpers/DeployApplicationTaskOperations.ts#L160
> 
> So the deployments may still be succeeding but the SDK fails to continue polling after it gets throttled. 
> 
> By default, the DescribeEnvironments and DescribeEvents APIs have a limit of 2 calls/sec with a burst of 15 calls/sec. As a result, if you are performing multiple deployments at exactly the same time, it is certainly possible that they're being throttled due to these rate limits. 
> 
> In order to proceed with this, can you please collect the Cloudtrail logs when you see the same error again. We need to make sure that we are looking at the correct API call which is originating from the SDK. I will send the logs to the service team and they will see if the limit increase is required in this situation. API rate limit is different from other service limits, and we need to ask the service team to push the code changes for the account which takes some time and it's a bit long process.
> 
> Please do include the region, timeframe, account number when you send us the Cloudtrail logs. 
> 
> As mentioned before:
> 
> You can use AWS Cloudtrail to record all the API calls. AWS CloudTrail is a web service that records AWS API calls for your account and delivers log files to you. The recorded information includes the identity of the API caller, the time of the API call, the source IP address of the API caller, the request parameters, and the response elements returned by the AWS service.
> 
> 
> Once the data has been uploaded correctly, please reply to this case to solicit a review of the data provided.
> 
> 
> 
> Once I have the Cloudtrail logs, I will contact the service team to get the help related to API rate limit. 
> If you have any additional queries or concerns, please do not hesitate to let me know. I'd be happy to help further!
> Thank you and have a nice day!
> 
> Best regards,
> 
> Amazon Web Services

I have uploaded the logs as requested and I am awaiting further action from the AWS side. I will keep this issue updated with any resolution.

**Comment by steveataws** [comment]
My initial debugging is done in VSCode, where I set up a configuration specific to the task. Once that's all running fine, I create a packaged version of the tools and install into a local test instance of TFS2017 and run the task to fine tune the update (eg messages I missed formatting correctly, or task parameter help markdown etc).

Here's a sample launch.json entry for debugging the S3 Upload task that you can use as a basis if you like - just be sure to never check your launch.json file into source control with real keys in it!

```
{
    "request": "launch",
    "protocol": "inspector",
    // Name of configuration; appears in the launch configuration drop down menu.
    "name": "Test S3 Upload Task",
    // Type of configuration. Possible values: "node", "mono".
    "type": "node",
    // Workspace relative or absolute path to the program.
    "program": "${workspaceRoot}/Tasks/S3Upload/S3Upload.ts",
    // Automatically stop program after launch.
    "stopOnEntry": false,
    // Command line arguments passed to the program.
    "args": [],
    // Workspace relative or absolute path to the working directory of the program being debugged. Default is the current workspace.
    "cwd": "${workspaceRoot}/Tasks/S3Upload",
    // Workspace relative or absolute path to the runtime executable to be used. Default is the runtime executable on the PATH.
    "runtimeExecutable": null,
    // Optional arguments passed to the runtime executable.
    "runtimeArgs": [
        "--nolazy"
    ],
    // Environment variables passed to the program.
    "env": {
        "INPUT_AWSCREDENTIALS": "68235771-c9d0-4c09-8f15-3b650be8c456",
        "NODE_TLS_REJECT_UNAUTHORIZED": "0",
        // !!BE SURE TO NEVER CHECK YOUR LAUNCH.JSON FILE INTO ANY SOURCE CONTROL!!
        "ENDPOINT_AUTH_68235771-c9d0-4c09-8f15-3b650be8c456": "{\"parameters\":{\"username\":\"ACCESS_KEY_HERE\",\"password\":\"SECRET_KEY_HERE\"}}",

        // specific arguments for the task
        "INPUT_BUCKETNAME": "mybucket",
        "INPUT_SOURCEFOLDER": "C:/somepath",
        "INPUT_GLOBEXPRESSIONS": "*.*",
        "INPUT_TARGETFOLDER": "s3prefix_value",
        "INPUT_REGIONNAME": "us-west-2",
        "INPUT_CREATEBUCKET": "false"
    },
    // Use JavaScript source maps (if they exist).
    "sourceMaps": true,
    "outFiles": [
        "${workspaceRoot}/_build/Tasks/S3Upload/*.js"
    ],
    "console": "internalConsole"
}
```

**Comment by systemsymbiosis** [comment]
Excellent Steve, I appreciate the tips! I will try this out as soon as I have a chance. Hopefully I can get sufficient progress to the point where I may be able to contribute a fix for this issue.

**Comment by systemsymbiosis** [comment]
Hi Steve,

I still have not had time to try and debug this but today I got another response from AWS support so I thought it best to share it here.

> Thank you for you patience and apologies for the delay in getting back to you. 
> 
> I have heard back from the service team. They have some further questions related to the use case. 
> 
> The large call rate to ListTagsForResource is causing the throttling on DescribeEvents and DescribeEnvironments since these APIs share the same bucket.
> 
> We can see that you are not making many update tags API call, so the tags shouldn't be changing that often.
> 
> > Can you please give me some information on the use case behind calling ListTagsForResource so much? 
> > Is it possible to reduce the call rate on it?
> 
> I will look forward to hear back from you. Once I have the details, I will forward it to the service team. 
> If you have any additional queries or concerns, please do not hesitate to let me know. I'd be happy to help further!
> Thank you and have a nice day!
> 
> Best regards,
> 
> Amazon Web Services

Many thanks

Austin

**Comment by steveataws** [comment]
I grepped through the codebase for the tools and we don't call the ListTagsForResource api in the deployment task, so I don't know where that's coming from.

**Comment by systemsymbiosis** [comment]
Thanks for the reply Steve. The mystery continues! I have notified AWS support and we will see how this progresses.
