### ISSUE TITLE
Beanstalk:  Application doesn't exist error

### ISSUE THREAD

**Issue by lukewis** [aws/aws-vsts-tools#64]
Our releases were working fine until a few days ago.  Now when we attempt to publish a new beanstalk version we get an "Application <Name> does not exist" error (Say "Foo" for the sake of argument).

If I search for the application via the AWS CLI, I can indeed find the application:
`aws elasticbeanstalk describe-applications --application-names Foo`
`
{
    "Applications": [
        {
            "ApplicationName": "Foo", 
`
Looking at the code, I'm wondering if we're hitting an exception (due to permissions, etc), but nothing gets logged due to the empty catch block either here: https://github.com/aws/aws-vsts-tools/blob/120ec73d1ac4bb6dd4dc17bbe4ba6bb534d392b9/Tasks/Common/beanstalkutils/beanstalkutils.ts#L137.

Could you add some additional logging in this catch block?  Do you have any other suggestions to troubleshoot this issue?

**Comment by steveataws** [comment]
Is this using the existing deploy task, or with the new create app version task?

**Comment by lukewis** [comment]
It's using the existing deploy task

**Comment by lukewis** [comment]
Though I also tried the new create app version task and seeing the same error with that task.

**Comment by steveataws** [comment]
Testing the new diagnostic logging, should have a release available shortly.

**Comment by steveataws** [comment]
1.0.20 is now on the marketplace; curious to know if it shows any error message for you or reports more than 1 application in the query.

**Comment by lukewis** [comment]
Thanks for the quick turnaround, @steveataws !  The logging definitely helped.  There error I'm seeing is:
`2018-02-12T22:21:55.7825570Z DescribeApplications: error Foo returned querying for existence of application SignatureDoesNotMatch: Signature expired: 20180212T222155Z is now earlier than 20180212T222200Z (20180212T222700Z - 5 min.)`
My initial guess is that the clock on our build server is off, but I won't be able to verify until tomorrow when the IT department is back in the office.  I'll update when I know more.

**Comment by lukewis** [comment]
I confirmed today that it was an incorrect clock on the build machine causing the issue.  The additional diagnostic logging that you added really helped clear things up.  Thanks @steveataws !

**Comment by steveataws** [comment]
Thanks for confirming!
