### ISSUE TITLE
Elastic Beanstalk Task Reports Success When Beanstalk Logs Show Errors

### ISSUE THREAD

**Issue by alpacamybags118** [aws/aws-vsts-tools#66]
Today, I ran into a particularly strange issue when using the Elastic Beanstalk task.

In TFS, the task would run and show as successful, but the code changes would not reflect when hitting the endpoint associated with the beanstalk stack. We were pretty perplexed, but when we looked at the actual logs in the beanstalk environment, we found this:

![image](https://user-images.githubusercontent.com/16386559/36569378-99d059da-17fb-11e8-999b-1ecc4f3012ac.png)

We ended up having to make a change to the assumed role in that account in order for the deployment to actually "work". I feel like this should have reflected as a failure in TFS as well. Is there any reason why the task would have reported the deployment as successful when the elastic beanstalk logs reported errors?

I am using the ASP.NET Core Deployment Bundle Type within the task. I have not seen this issue with other bundle types selected, although I haven't really had any other use case to test this with.

**Comment by steveataws** [comment]
That's a pretty odd error to happen - I need to re-check the task code, and the .NET CLI extension that it calls for this type of bundle. The polling on events quits when we get a successful or error state and reports it up the call stack accordingly, For the task to have reported success, I would expect we get a 'good' final state from the service but for some reason the environment then transitioned to unhealthy.

Have you been able to retrieve logs from the environment instance to see if there are any further clues to what happened on the instance itself?

**Comment by alpacamybags118** [comment]
Sorry for the delayed response on this, but I had someone who can access the account look at environment logs, but we didn't really see anything special. I'm wonder if its maybe because it was a permission specific issue when deploying? Or should that appear in the environment instance itself?

**Comment by hunterwerlla** [comment]
There was no additional info attached and the ticket is over a year old, if you have any additional issues, please open a new issue.
