### ISSUE TITLE
S3 Upload - Multiple Locations?

### ISSUE THREAD

**Issue by mwilliams12** [aws/aws-vsts-tools#67]
Amazon Support,

Can the S3 Upload build task have multiple locations (1 to many, not 1-1)? We normally set a bucket per location and then add the correct security. We would like to segregate for (1) users and (2) teams if possible. 

If possible, would you be able to provide any documentation on how to handle multiple AWS accounts in VSTS?

Best Regards,

Michael W.

**Comment by steveataws** [comment]
The current upload task writes to a single bucket and either a single object key or key hierarchy (when uploading multiple files) at a time. To write to different buckets or different key prefix roots you just need to use multiple instances of the task.

To use the task for different teams, you can set up multiple service endpoints each containing the relevant credentials or role scoped to the particular team. Then you use multiple instances of the upload task, each using the credential endpoint it needs to give it access to the resources it needs to update.

**Comment by steveataws** [comment]
I don't see any immediate requirements on the tools for this issue so an closing. Feel free to reopen if work needs to be done in the tools.
Thanks!
