### ISSUE TITLE
Deploy Cloudformation using YAML ?

### ISSUE THREAD

**Issue by clakech** [aws/aws-vsts-tools#68]
Hello,

Do you plan or are interested in deploying a cloudformation stack using yaml format ? 

For now, only json is possible:
https://github.com/aws/aws-vsts-tools/blob/120ec73d1ac4bb6dd4dc17bbe4ba6bb534d392b9/Tasks/CloudFormationCreateOrUpdateStack/helpers/CreateOrUpdateStackTaskOperations.ts#L466

I may do a PR

**Comment by steveataws** [comment]
Sure, we'd be happy to take a PR for this if you'd like to contribute!

**Comment by clakech** [comment]
Let's follow up discussion in this PR https://github.com/aws/aws-vsts-tools/pull/70
