### ISSUE TITLE
ECR Pull 

### ISSUE THREAD

**Issue by sddev-dotnet** [aws/aws-vsts-tools#69]
I am trying to pull a container from ECR using a VSTS agent and am not able to get it working. I have tried using the AWS CLI task and configuring the aws ecr get-login command but it just drops the docker command into the log (I need to eval$()) the output to be able to actually execute the command that comes out. 

I also tried using a  shell script: 
```
reg_id=$(cut -d'.' -f1<<<$1)
login_cmd=$(aws ecr get-login --registry-ids $reg_id --no-include-email --region $3)
sudo $login_cmd
sudo docker pull $1 
```

but I wasn't able to assume the role on my account (I need the connected service to be able to run the command). 

My goal here is to pull a container from my dev ECR, tag it as a release candidate, and push it to my production ECR. It would be great if there was just a Pull From ECR task I could use, but any help would be appreciated.

**Comment by steveataws** [comment]
Apologies for the time taken to respond.

Adding a task to pull from ECR sounds interesting, but probably won't get added for a little while. In the meantime did you manage to get the command line working?

**Comment by hunterwerlla** [comment]
This was added as a feature as part of the 1.5 release
