### ISSUE TITLE
CloudFormation Create/Update Stack: Inline Parameters

### ISSUE THREAD

**Issue by cameronattard** [aws/aws-vsts-tools#71]
Hi,

It would be great to have the option of specifying CloudFormation stack parameters inline in the build definition without having to point it to a parameters file.

Thanks!

**Comment by steveataws** [comment]
Glad you're all enjoying the tools. This seems like a straightforward request we can add without any breaking changes. I'll see where we can fit it into our schedules.

**Comment by steveataws** [comment]
Update released in v1.0.21, resolving.
