### ISSUE TITLE
Description in BeanstalkCreateApplicationVersion is ignored

### ISSUE THREAD

**Issue by Zyklop** [aws/aws-vsts-tools#72]
There is a parameter description in the "Beanstalk Create Version" task. Sadly it doesn't work. According to CreateApplicationVersionTaskOperations.ts, the description parameter isn't used anywhere. Please also submit this parameter with the request, so we can provide a helpful description for the version.

**Comment by steveataws** [comment]
Oh, that's a silly bug - apologies. Fixed pending release next week.

Thanks for reporting it!

**Comment by steveataws** [comment]
Fixed and released in v1.0.21, resolving.
