### ISSUE TITLE
In Lambda Publish Wizard, Dead-Letter-Queue is Required

### ISSUE THREAD

**Issue by ddrinka** [aws/aws-vsts-tools#77]
I do not wish to utilize a Dead Letter Queue.  Choosing the option <no dead letter queue> in the Lambda Publish wizard allows me to move foward, but then the publish fails with "DLQ must start with arn...".  This only occurs when publishing to a new function, not updating an existing one.

**Comment by steveataws** [comment]
Thanks for reporting the issue - just to be sure, you are using the Lambda .NET Core deployment task from VSTS/TFS, not the Publish to AWS Lambda in our Visual Studio toolkit?

**Comment by ddrinka** [comment]
I'm using the Node.js integration:
![image](https://user-images.githubusercontent.com/1297262/39791144-a339118a-52ff-11e8-9a29-73f1a892b760.png)

**Comment by steveataws** [comment]
Oh, you're talking about our toolkit for Visual Studio, not the Team Services integration (which is what this repo is for). Regardless, I'll take a look as I work on both.

In future, you might want to use the AWS .NET SDK repo for posting issues about the toolkit - https://github.com/aws/aws-sdk-net.

**Comment by ddrinka** [comment]
Apologies.  I'll create a ticket over there and link here.

**Comment by ddrinka** [comment]
Moved to https://github.com/aws/aws-sdk-net/issues/949
