### ISSUE TITLE
A WebException with status SecureChannelFailure

### ISSUE THREAD

**Issue by Neuroforge** [aws/aws-vsts-tools#78]
Hello,

I have a .NET Core application built with VS2017.

Until recently, i have been publishing directly to the Elastic Beanstalk instance.

- Right click on project.
- Select Publish to AWS Elastic Beanstalk.
- Select instance
- Next
- Next
- Finish

This has worked great up until now using this Tutorial

https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_NET.quickstart.html

However, for the past few days i have been unable to update the instance.

> ..zipping publishing directory
> ..deployment package created successfully...
> ...starting redeployment to AWS Elastic Beanstalk environment 'XXXXXXXXXXX-env'
> ....uploading application deployment package to Amazon S3
> ......uploaded 0% of application deployment package
> ......uploaded 1% of application deployment package
> ......uploaded 2% of application deployment package
> ......uploaded 3% of application deployment package
> ......uploaded 4% of application deployment package
> ......uploaded 5% of application deployment package
> ......uploaded 6% of application deployment package
> Publish to AWS Elastic Beanstalk failed with exception: A WebException with status SecureChannelFailure was thrown.,
> Inner Exception Message: The request was aborted: Could not create SSL/TLS secure channel.
> Error publishing application: Unhandled error during deployment

I have updated VS2017 and the AWS VSTA Tools with no improvement.

AWS Toolkit for Visual Studio 2017
Version 1.14.3.0

Visual Studio 2017
Version 15.6.3

The only real changes recently is that i moved offices and currently we only have a dsl connection (Fibre is to be installed next week).

Any thoughts?

Regarda

**Comment by steveataws** [comment]
I'm not sure what's going on here, but it seems external to the tools. Is your new network behind some form of a proxy that could be interfering? Do any of the other tasks work? Since you have the VS toolkit installed too, is the AWS Explorer operational in this new environment?

**Comment by steveataws** [comment]
This issue relates to the AWS Toolkit for Visual Studio, not the Team Services tools in this repo. I don't know why I didn't notice this when opened, I suspect a lack of caffeine. Hopefully the problem lay in your new networking setup and has now been resolved since there was no follow up.

If you're still getting a problem, I suggest opening an issue on the main .NET sdk repo (https://github.com/aws/aws-sdk-net). Resolving this one as there's nothing we can do in the VSTS tools to help.
