### ISSUE TITLE
Unable to install on TFS2018

### ISSUE THREAD

**Issue by jorge-duarte** [aws/aws-vsts-tools#79]
Hi, I can't install AWS Tools for VSTS/TFS on my TFS 2018 Update 2 instance. The VSIX installer is throwing 

> This extension is not installable on any currently installed products.

But in documentation explains that is valid for Visual Studio Team Services or Team Foundation Server 2015 Update 3 (or higher). When I try to install from Web Interface it take a few minutes and die saying that something went wrong. In the same way, I tried with temporary version of extension but with same results.

I attach the installation log (Spanish):

> 17/05/2018 12:57:59 - Microsoft VSIX Installer
> 17/05/2018 12:57:59 - -------------------------------------------
> 17/05/2018 12:57:59 - vsixinstaller.exe version:
> 17/05/2018 12:57:59 - 15.7.103+gdea0b20b76
> 17/05/2018 12:57:59 - -------------------------------------------
> 17/05/2018 12:57:59 - Command line parameters:
> 17/05/2018 12:57:59 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\administrador.EZSOLUTIONS\Desktop\Software\Team Foundation Server 2018\amazonwebservices.aws-vsts-tools-1.0.18-tfs2015.vsix
> 17/05/2018 12:57:59 - -------------------------------------------
> 17/05/2018 12:57:59 - Microsoft VSIX Installer
> 17/05/2018 12:57:59 - -------------------------------------------
> 17/05/2018 12:58:02 - Initializing Install...
> 17/05/2018 12:58:02 - Detalles de la extensión...
> 17/05/2018 12:58:02 - 	Identifier         : aws-vsts-tools
> 17/05/2018 12:58:02 - 	Name               : AWS Tools for Microsoft Visual Studio Team Services
> 17/05/2018 12:58:02 - 	Author             : amazonwebservices
> 17/05/2018 12:58:02 - 	Version            : 1.0.18
> 17/05/2018 12:58:02 - 	Description        : Tasks for Amazon S3, AWS Elastic Beanstalk, AWS CodeDeploy, AWS Lambda and AWS CloudFormation and more, and running commands in the AWS Tools for Windows PowerShell module and the AWS CLI.
> 17/05/2018 12:58:02 - 	Locale             : en-US
> 17/05/2018 12:58:02 - 	MoreInfoURL        : 
> 17/05/2018 12:58:02 - 	InstalledByMSI     : False
> 17/05/2018 12:58:02 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
> 17/05/2018 12:58:02 - 
> 17/05/2018 12:58:03 - 	SignatureState     : InvalidSignature
> 17/05/2018 12:58:03 - 	SignedBy           : Amazon.com, Inc.
> 17/05/2018 12:58:03 - 	Certificate Info   : 
> 17/05/2018 12:58:03 - 		-------------------------------------------------------
> 17/05/2018 12:58:03 - 		[Subject]       : CN="Amazon.com, Inc.", O="Amazon.com, Inc.", L=Seattle, S=Washington, C=US
> 17/05/2018 12:58:03 - 		[Issuer]        : CN=Symantec Class 3 SHA256 Code Signing CA - G2, OU=Symantec Trust Network, O=Symantec Corporation, C=US
> 17/05/2018 12:58:03 - 		[Serial Number] : 2B778385004F4CA691C07F3590C07B7F
> 17/05/2018 12:58:03 - 		[Not Before]    : 09/07/2017 19:00:00
> 17/05/2018 12:58:03 - 		[Not After]     : 10/07/2020 18:59:59
> 17/05/2018 12:58:03 - 		[Thumbprint]    : D2038C3D2E59604D9AD05674B21B53EA40ACE63F
> 17/05/2018 12:58:03 - 
> 17/05/2018 12:58:03 - 	Productos admitidos : 
> 17/05/2018 12:58:03 - 		Microsoft.VisualStudio.Services
> 17/05/2018 12:58:03 - 			Version : 
> 17/05/2018 12:58:03 - 
> 17/05/2018 12:58:03 - 	Referencias        : 
> 17/05/2018 12:58:03 - Detalles de la firma...
> 17/05/2018 12:58:03 - 	Extension is signed with an invalid signature.
> 17/05/2018 12:58:03 - 
> 17/05/2018 12:58:03 - Buscando productos aplicables...
> 17/05/2018 12:58:03 - Producto instalado encontrado: Microsoft Visual Studio 2010 Ultimate
> 17/05/2018 12:58:03 - Producto instalado encontrado: Microsoft Visual Studio Enterprise 2015
> 17/05/2018 12:58:03 - Producto instalado encontrado: Microsoft Visual Studio Professional 2015
> 17/05/2018 12:58:03 - Producto instalado encontrado: Microsoft Visual Studio Community 2015
> 17/05/2018 12:58:03 - Producto instalado encontrado: Microsoft Visual Studio 2015 Shell (Integrated)
> 17/05/2018 12:58:03 - Producto instalado encontrado: Ubicación global
> 17/05/2018 12:58:03 - Producto instalado encontrado: ssms
> 17/05/2018 12:58:03 - Producto instalado encontrado: Visual Studio Enterprise 2017
> 17/05/2018 12:58:03 - VSIXInstaller.NoApplicableSKUsException: Esta extensión no se puede instalar en ninguno de los productos instalados actualmente.
>    en VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
>    en VSIXInstaller.App.Initialize(Boolean isRepairSupported)
>    en VSIXInstaller.App.Initialize()
>    en System.Threading.Tasks.Task`1.InnerInvoke()
>    en System.Threading.Tasks.Task.Execute()

**Comment by jorge-duarte** [comment]
Hi again and thank you for your quick response. It's as if that's looking for some concrete version of Team Foundation Server that does not found..

**Comment by steveataws** [comment]
I think based on the log file (thanks!) that you are in fact trying to use the wrong installer. C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe is Microsoft's installer for Visual Studio IDE extensions - not Team Foundation Server.

This seems to be confirmed in that I got as far as installing TFS2018 U2 onto a system but don't yet have Visual Studio installed, so when I double click the downloaded vsix file I don't get launched into the VS installer (instead I get prompted to select an app to open the file with - none of them are relevant).

When you downloaded the vsix file from the marketplace, a couple of instructions are displayed - if you follow these you should be able to get up and running (they are exactly what I followed):

* Navigate to the Team Foundation Server Extensions page on your server. (For example, http://someserver:8080/tfs/_gallery/manage)
* Click upload new extension and select the file you have just downloaded.
* After the extension has successfully uploaded, click Install and select the Team Project Collection to install into.

**Comment by jorge-duarte** [comment]
I tried to install again from TFS site and it never finish to validate.

![image](https://user-images.githubusercontent.com/39383564/40210420-6ba2d38e-5a0a-11e8-8ef0-05e31d30106e.png)

**Comment by jorge-duarte** [comment]
I do not understand how he did it, but that he did. After 1 hour (and some updates from windows update and restarts) the Verifying label change to Installed. Thank you.

**Comment by steveataws** [comment]
Good to hear you are up and running. I've not experienced any further issues so I don't think there is work to do here, going to resolve the issue. Feel free to re-open (or open a new issue) if you run into any further problems.
