### ISSUE TITLE
AWS CloudFormation Create/Update Stack

### ISSUE THREAD

**Issue by Asanga-apsis** [aws/aws-vsts-tools#8]
Hi,
I'm trying to use the AWS CloudFormation Create/Update Stack task. 
It says "Template File" is a mandatory field. But there is no input box for Template Files. 
And I cannot save the template without entering Template file name.
![screen shot 2017-08-24 at 10 48 28](https://user-images.githubusercontent.com/12711317/29658043-d2560754-88b9-11e7-8599-2fd3f66a8ccd.png)

**Comment by steveataws** [comment]
I just checked a definition I was working with yesterday and both the field and browse (...) option appear to be present and correct. If I shrink the window enough, I lose the ... option, but never the border on the template and parameters fields, or the fields themselves, so I don't know what's going wrong for you:

![image](https://user-images.githubusercontent.com/2090449/29673097-03cdb4e2-88a3-11e7-83e7-e65c311baf5b.png)

You don't say what version you have installed, but can you uninstall and then install v1.0.4 that was released yesterday so we're on the same base?

**Comment by Asanga-apsis** [comment]
Thanks for the reply.
I'm using TFS 2017 Update 2 (On-premis). **Not the VSTS**. I installed the v1.0.4 and problem still exists. 
I tested on Chrome, FF, Safari & IE. All browsers have the same issue. Guessing it's something with Filepath type. But S3 upload task works fine (which also contain filePath filed)

**Comment by steveataws** [comment]
I set up a TFS2017 instance overnight and the good news is that I can repro your issue:

![image](https://user-images.githubusercontent.com/2090449/29723223-9889f9a8-8978-11e7-8012-89f40587f9aa.png)

The bad news is that I have no idea why filepath field types in this task are having issues, and in other tasks work just fine (unless it's something to do with having two alongside each other).

**Comment by steveataws** [comment]
D'oh, found it - TFS seems to be case sensitive to the field type string (filepath vs filePath), whereas VSTS is not.

I should have a fix out shortly once I cross-check all the other tasks.

**Comment by steveataws** [comment]
v1.0.5 is now available on the marketplace. I installed into both VSTS and on-premise TFS 2017 instances and the issue appears to be resolved, but please confirm so we can close the issue. Thanks!

**Comment by Asanga-apsis** [comment]
Hi Steve,
Thanks a lot for a quick response. 
I can confirm it is fixed with. 1.0.5.
Great job!!
