### ISSUE TITLE
Error while running AWS Lambda .NET Core Deployment Task

### ISSUE THREAD

**Issue by kevbite** [aws/aws-vsts-tools#80]
We seem to be getting the following error when running the deployment task:

```
2018-05-21T15:59:48.3073486Z Task         : AWS Lambda .NET Core Deployment
2018-05-21T15:59:48.3073691Z Description  : Build and deploy a Serverless .NET Core application or AWS Lambda function
2018-05-21T15:59:48.3073879Z Version      : 1.0.21
2018-05-21T15:59:48.3074024Z Author       : Amazon Web Services
2018-05-21T15:59:48.3074243Z Help         : Please refer to [AWS Lambda Developer Guide](https://docs.aws.amazon.com/lambda/latest/dg/) for more information on working with AWS Lambda.
2018-05-21T15:59:48.3074497Z ==============================================================================
2018-05-21T15:59:48.6353879Z 77ba38e3-79ed-42df-9b9b-2c74eb4ae652 exists true
2018-05-21T15:59:48.6398122Z Deploying Lambda project at D:\a\r1\a\_ProjectX.Audit Build\drop
2018-05-21T15:59:48.6416695Z Beginning dotnet restore
2018-05-21T15:59:48.6446617Z Path to tool: C:\Program Files\dotnet\dotnet.exe
2018-05-21T15:59:48.6478248Z [command]"C:\Program Files\dotnet\dotnet.exe" restore
2018-05-21T15:59:48.8334085Z MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
2018-05-21T15:59:48.8526334Z ##[error]Error: C:\Program Files\dotnet\dotnet.exe failed with return code: 1
2018-05-21T15:59:48.8569458Z ##[section]Finishing: Deploy to Lambda:  Development
```

I don't really get why it's trying to run `dotnet restore`?

We've set up a build pipeline to just pack up our .net core serverless application and then we've got another release pipeline to pick up the artifacts and deployment them to aws via this task.

![image](https://user-images.githubusercontent.com/5544715/40318343-2ff32fa4-5d1c-11e8-8d87-6c9860ca8c0c.png)

What I find weird is if I run it locally using `dotnet lambda deploy-serverless` using the following aguments it works totally fine:
```dotnet lambda deploy-serverless --package .\bin\Release\netcoreapp2.0\xxx.zip --template-parameters "xxx=aaa;yyy=bbb"```

**Comment by kevbite** [comment]
Ah OK I see what is going off now, the first step to this task is to run dotnet restore to pull in the cli tools package. As a workaround I've just hacked in a step before running this task to create a `temp.csproj` so that it can use the dotnet cli tools.

```Set-Content -Path ".\temp.csproj" -Value '<Project Sdk="Microsoft.NET.Sdk">
>>
>>   <PropertyGroup>
>>     <TargetFramework>netcoreapp2.0</TargetFramework>
>>   </PropertyGroup>
>>
>>   <ItemGroup>
>>     <DotNetCliToolReference Include="Amazon.Lambda.Tools" Version="2.1.3" />
>>   </ItemGroup>
>>
>> </Project>
>> '```

**Comment by steveataws** [comment]
Wouldn't it be simpler to add the tools reference to the your actual project, so you have access to the dotnet cli extensions for Lambda where ever you are using this project?

**Comment by kevbite** [comment]
We package our lambda application up using the following CLI command within our build agent:
```
dotnet lambda package --output-package ./package.zip
```
then we list them as artifacts to a build
then we release them using a completely separate pipeline within the release manager, this allows us to track release and also publish to multiple stacks.

**Comment by steveataws** [comment]
OK, that's what I'd expect. Is there anything needed from us on this issue or can we close it?

**Comment by kevbite** [comment]
No totally fine, just took a bit of working out how the plugin worked. 

The workaround works perfectly fine for just pulling in the CLI tool.

Thanks

**Comment by steveataws** [comment]
Don't think there is any work to do here, so resolving. Feel free to reopen if needed.

**Comment by kevbite** [comment]
Hey @angelo250, are you deploying a serverless application or just the lambda function? All I did was replicate what I was doing locally deploying it with the dotnet CLI. Here's a screenshot of our release task for deploying a serverless application, hope it's useful:

![image](https://user-images.githubusercontent.com/5544715/42727515-5cadee90-87a0-11e8-99d4-20117ecfaa3b.png)

**Comment by angelo250** [comment]
@kevbite it’s a stand-alone lambda function. I will try to deploy locally and see what I get. I’ll report back on Monday.

**Comment by kevbite** [comment]
@angelo250 looking at your logs it seems you're missing the `--package` argument to pass into the dotnet lambda CLI command, this will stop it trying to do a build and deploy, and just deploy the specified package instead.

**Comment by angelo250** [comment]
@kevbite that did it! Thank you! I had searched through the [source](https://github.com/aws/aws-extensions-for-dotnet-cli/blob/master/src/Amazon.Lambda.Tools/Commands/DeployFunctionCommand.cs) of deploy-function and found the package parameter but didn't find how to pass it to the lambda publish method. Is there an online reference?

**Comment by kevbite** [comment]
@angelo250 nope, I just found it from digging around and seeing how things work 👍

**Comment by steveataws** [comment]
Just to let you know, we have some changes coming that we believe significantly enhances these tasks to make packaging and subsequent deployment, from separate build or release pipelines, of Lambda functions and Serverless applications much easier.

I don't have a specific ETA I can share but I'm talking a matter of weeks, not months, before release. Hopefully this will make your lives a lot simpler :-)

**Comment by kevbite** [comment]
@steveataws that would be great, thanks for the information!

**Comment by angelo250** [comment]
@steveataws thank you! Looking forward to the release.
