### ISSUE TITLE
Create/Update Stack task times out after 60 minutes

### ISSUE THREAD

**Issue by ansariwn** [aws/aws-vsts-tools#85]
Hi,
Our stack creation takes more than 1 hour to complete. Unfortunately, the stack creation task times out after 60 minutes. I believe this is due to cloudformation.[waitFor](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudFormation.html#stackCreateComplete-waiter)('stackCreateComplete'... function that "waits for the stackCreateComplete state by periodically calling the underlying CloudFormation.describeStacks() operation every 30 seconds (at most 120 times)."

I have tried to update the VSTS task 'timeout' value (under Control Options section) but I don't think it is passed to Create/Update stack function. Can anyone please help with how to increase the timeout value? I get the following error in VSTS task output:

##[error]Error: Stack WE1-B1-CFN-373 failed to reach completion status, error: 'Resource is not in the state stackCreateComplete'

Please note that as per AWS [documentation ](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/troubleshooting.html#troubleshooting-resource-did-not-stabilize) we specify a service role to extend the timeout period (and pass it in to the VSTS task as 'Role ARN' value), however, I am not sure how the timeout period is extended as there is not place to set the timeout value for a service role.

**Comment by steveataws** [comment]
This is going to need a change to the task so a maximum wait period can be specified.

**Comment by ansariwn** [comment]
Submitted Pull Request #88 .

**Comment by steveataws** [comment]
Resolving,  included in v1.1.0 released Aug 2nd.
