### ISSUE TITLE
AWS Lambda Deploy Function task does not have .NET Core 2.1 available in runtime list

### ISSUE THREAD

**Issue by wlrichards** [aws/aws-vsts-tools#86]
AWS Lambda now supports .Net Core 2.1 as a runtime but this task does not allow choosing it for deployment.

IMHO the current drop down list should be an entry field instead so the task does not need to be updated for new runtimes

**Comment by steveataws** [comment]
The change to include the 2.1 runtime is done and tested, just pending release as it is currently included in a bunch of other, larger updates, which we're trying to schedule.

However I totally agree on making the field editable with drop down selection capability, so will work that into the change too. Sorry for the inconvenience, we updated a bunch of tools on release day and this particular tool was a miss on our part.

**Comment by steveataws** [comment]
Implemented as editable field with drop down options, will be included in next release of the tools.

**Comment by steveataws** [comment]
Resolving,  included in v1.1.0 released Aug 2nd.
