### ISSUE TITLE
Deploy with CodeDeploy timesout after 30 minutes

### ISSUE THREAD

**Issue by kevbite** [aws/aws-vsts-tools#87]
We're having problems where our `Deploy with CodeDeploy` task is failing with a timeout error after 30 minutes. 

```
2018-07-18T09:01:23.4138042Z ##[section]Starting: Deploy with CodeDeploy: Our-Application
2018-07-18T09:01:23.4144877Z ==============================================================================
2018-07-18T09:01:23.4145058Z Task         : AWS CodeDeploy Application Deployment
2018-07-18T09:01:23.4145403Z Description  : Deploys an application to Amazon EC2 instance(s) using AWS CodeDeploy
2018-07-18T09:01:23.4145574Z Version      : 1.0.21
2018-07-18T09:01:23.4145720Z Author       : Amazon Web Services
2018-07-18T09:01:23.4146219Z Help         : Please refer to [AWS CodeDeploy User Guide](https://docs.aws.amazon.com/codedeploy/latest/userguide/) for more information on working with AWS CodeDeploy.
2018-07-18T09:01:23.4146431Z ==============================================================================
2018-07-18T09:01:23.9329451Z 528b9e3-ffff-0000-1234-a87a5a8a6a95 exists true
2018-07-18T09:01:24.5584238Z Deploying the new revision
2018-07-18T09:01:25.1872502Z Started deployment of new revision to deployment group ReleaseCandidate for application Our-Application, deployment ID d-abcdefghi
2018-07-18T09:01:25.1876937Z Waiting for deployment to complete
2018-07-18T09:32:10.7191948Z ##[error]Unhandled: Deployment failed Our-Application Resource is not in the state deploymentSuccessful
2018-07-18T09:32:10.7257984Z ##[section]Finishing: Deploy with CodeDeploy: Our-Application
```

However, within the control section of the task, the timeout is set to `infinite`
![image](https://user-images.githubusercontent.com/5544715/42875754-7f6b2090-8a7c-11e8-8071-9ba12e428dc7.png)

Is there a way to increase this timeout?

Thanks

**Comment by kevbite** [comment]
Digging around in the code it looks like this just called the [JavaScript SDK `waitfor`](https://github.com/aws/aws-vsts-tools/blob/master/Tasks/CodeDeployDeployApplication/helpers/DeployApplicationTaskOperations.ts#L217)

Which is documented as:
>Waits for the deploymentSuccessful state by periodically calling the underlying CodeDeploy.getDeployment() operation every 15 seconds (at most 120 times).
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CodeDeploy.html#waiter_details

So it seems that's where the 30 minutes is coming from (15 seconds * 120 times = 1800 seconds = 60 minutes).

**Comment by ansariwn** [comment]
Hi @kevbite ,

Hope you are doing well.

This issue is similar to my issue #85 . I have just submitted a pull request #88 to resolve it. If my PR is successful you can probably do something similar.

I would have preferred to submit a PR to AWS JavaScript SDK team but fixing the function in SDK seems lot harder so my PR #88 is kind of a work around perhaps.

**Comment by kevbite** [comment]
@ansariwn just checked out your PR, seems a decent workaround tbh, I do find it is weird that the SDK doesn't allow this to be configurable.

If it works for creating stacks then be good to get the same code into the CodeDeploy task :-)

**Comment by steveataws** [comment]
I've left a comment on the PR but worth repeating here, we have updated the CloudFormation task to allow for a custom timeout and it will be included in a release we're currently hoping to ship in the next couple weeks. My bad that I forgot to respond on the issue that we had a fix pending release.

We've not done it yet for CodeDeploy however - so @ansariwn, if you feel like revising your PR to address the CodeDeploy task instead we'd be delighted to take it. I put examples of how we did it for CloudFormation on the PR discussion if you want to remain broadly compatible.

**Comment by ansariwn** [comment]
Hi @kevbite ,

I have made the required changes to the CodeDeploy VSTS task. Would you be interested to test it? I don't have a valid test case. If yes then please send me your VSTS account name and I will privately share the extension with your account.

**Comment by kevbite** [comment]
@ansariwn would happily test it, can you share it to this account - bigchange.visualstudio.com

Thanks!

**Comment by ansariwn** [comment]
Hi @kevbite ,
I have now shared the extension with the vsts account. Please let me know when you are done.

Many thanks for the help!

**Comment by kevbite** [comment]
@ansariwn do you know how I enable it/see it?

**Comment by kevbite** [comment]
Well, ours look completely different but I found it 👍 I was looking at the project settings instead of the account settings.

![image](https://user-images.githubusercontent.com/5544715/43072068-ae6f4f8a-8e6c-11e8-8c07-5748510c8988.png)

However I'm getting an issue with installing it as it has conflicting tasks, Is there a way to run this side by side with the other version?

>A task definition with id '081ccf10-2f14-48dd-9bd0-892b8975d24f', name 'AWSCLI' and version '1.0.21' has already been uploaded by extension 'aws-vsts-tools'. To upload the task, provide a different task id.

**Comment by kevbite** [comment]
Added and tested, seems to be working fine 👍

**Comment by ansariwn** [comment]
That's great news! I will submit the PR shortly. Many thanks

**Comment by steveataws** [comment]
Resolving,  included in v1.1.0 released Aug 2nd.

**Comment by krlinus** [comment]
> Digging around in the code it looks like this just called the [JavaScript SDK `waitfor`](https://github.com/aws/aws-vsts-tools/blob/master/Tasks/CodeDeployDeployApplication/helpers/DeployApplicationTaskOperations.ts#L217)
> 
> Which is documented as:
> 
> > Waits for the deploymentSuccessful state by periodically calling the underlying CodeDeploy.getDeployment() operation every 15 seconds (at most 120 times).
> 
> https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CodeDeploy.html#waiter_details
> 
> So it seems that's where the 30 minutes is coming from (15 seconds * 120 times = 1800 seconds = 60 minutes).

Sorry if this is not relevant now, but 1800 / 60 is 30 not 60 minutes.

**Comment by kevbite** [comment]
Yep @krlinus, typo! 🤷
