### ISSUE TITLE
SNS Send Message task is not finding Topic by ARN

### ISSUE THREAD

**Issue by tastydew** [aws/aws-vsts-tools#89]
I have a task that will notify subscribers when a build is deployed. I have my credentials set up properly and I enter the ARN in the following way:

![image](https://user-images.githubusercontent.com/5760906/42952339-3ad620c2-8b46-11e8-9cca-0688ce8f1ee0.png)

However I am always getting the following error...

![image](https://user-images.githubusercontent.com/5760906/42952671-0495cda4-8b47-11e8-8b77-50d0f7f3ae0d.png)

Should I be entering the ARN in a different format? The documentation says nothing about this.

**Comment by steveataws** [comment]
At first glance it looks correct, although the (understandable) redaction makes it hard to be sure :-)

Poking around on my test server to see if we broke something somewhere, although this task hasn't changed for some time. I'll get back asap.

**Comment by steveataws** [comment]
Everything seems ok on my integration test server -

```
******************************************************************************
Starting: Send Message: arn:aws:sns:us-west-2:xxx...xxx:VSTSBuildTest
******************************************************************************
==============================================================================
Task         : AWS Send Message
Description  : Sends a message to an SNS topic or SQS queue
Version      : 1.0.21
Author       : Amazon Web Services
Help         : Please refer to [Amazon Simple Queue Service](https://aws.amazon.com/documentation/sqs/) and [Amazon Simple Notification Service](https://aws.amazon.com/documentation/sns/) documentation for working with these services.
==============================================================================
fdb34ae1-515a-400d-b88c-bf0fdd6b22a7 exists true
Sending message to topic arn:aws:sns:us-west-2:xxx...xxx:VSTSBuildTest
Successfully completed sending the message
******************************************************************************
Finishing: Send Message: arn:aws:sns:us-west-2:xxx...xxx:VSTSBuildTest
******************************************************************************
```

Downstream email and SQS recipients all received the message that was sent to the topic too.

Is it possible the account that your build is running under doesn't have permissions to call the GetTopicAttributes api for SNS (which is what the task uses to benignly verify that the topic exists)?

**Comment by tastydew** [comment]
It was my permissions! I had the wrong permission set for SNS (doh!). It just wasnt showing up in the log as an authentication failure. Possibly because I was running it asynchronously? Regardless, thanks for the help!
