### ISSUE TITLE
CloudFormation Deploy - Warning for no changes

### ISSUE THREAD

**Issue by JeffRausch** [aws/aws-vsts-tools#91]
We're using the **CloudFormation Create/Update Stack** task (without a Change Set) in VSTS.  Is it possible to not log a warning when there's no changes to a CloudFormation stack on deployment?  Even if we had the option to turn it on or off it would be helpful.
With the new VSTS UI it shows the phase as having 1 issue even if it's a warning, which I personally don't like either, but having a warning show for something that's perfectly fine seems a bit misleading to us.

I do see why it was originally put in ( see https://github.com/aws/aws-vsts-tools/issues/28 ) but it would be nice to be able to have a release without any issues showing when it's finished if possible.

**Comment by steveataws** [comment]
Sure, we'll take a look.

**Comment by steveataws** [comment]
Implemented with a new task option, 'Log warning during stack update if AWS CloudFormation reports no work to be done' (default checked). This will be included with the next update which is in the final stages of i-dotting and t-crossing.

**Comment by JeffRausch** [comment]
Awesome.  Thanks for the quick work!  I'll be on the lookout for it.

**Comment by steveataws** [comment]
Resolving,  included in v1.1.0 released Aug 2nd.

**Comment by JeffRausch** [comment]
I'm not sure if this change broke the changes done for issue #28 but now if I deploy a stack that uses a change set and there are no changes I get an error and the release fails.  I didn't notice any options that I could change other than the "Log warning during stack update..." that was added for this issue (#91).  There is a "Continue on error" option under Control Options but I don't think we want to do that in case there are other issues with the CF deployment.
The deployment without a change set works as expected.

> 2018-08-21T12:36:43.7456643Z Waiting for change set Release-20180821-2 to be validated for stack CF-XXXXXXXXXX

> 2018-08-21T12:37:14.0340548Z Change set creation request failed with error: 'Stack CF-XXXXXXXXXX failed to create successfully from the change set Release-20180821-2. Error: 'Resource is not in the state changeSetCreateComplete'' Error: Stack CF-XXXXXXXXXX failed to create successfully from the change set Release-20180821-2. Error: 'Resource is not in the state changeSetCreateComplete'
2018-08-21T12:37:14.0361661Z     at .<anonymous> (D:\VSTS_Worker01\_work\_tasks\CloudFormationCreateOrUpdateStack_7ef7cdfa-aa45-42c5-93c8-d7603643dd99\1.1.3\CloudFormationCreateOrUpdateStack.js:9:23778)

> 2018-08-21T12:37:14.0415842Z ##[error]Error: Stack CF-XXXXXXXXXX failed to create successfully from the change set Release-20180821-2. Error: 'Resource is not in the state changeSetCreateComplete'
2018-08-21T12:37:14.0434437Z     at next (native)
2018-08-21T12:37:14.0436376Z     at o (D:\VSTS_Worker01\_work\_tasks\CloudFormationCreateOrUpdateStack_7ef7cdfa-aa45-42c5-93c8-d7603643dd99\1.1.3\CloudFormationCreateOrUpdateStack.js:9:12374)
2018-08-21T12:37:14.0465109Z     at process._tickDomainCallback (internal/process/next_tick.js:135:7)
