### ISSUE TITLE
Lambda Invoke on DynamoDB returning "ExpressionAttributeValues" error

### ISSUE THREAD

**Issue by tastydew** [aws/aws-vsts-tools#92]
I seem to be running into an issue when attempting to invoke a lambda function via VSTS. I am not sure if I am formatting something incorrectly, but I have tried all sorts of methods to format my payload and still get the same error.... Am I missing something with my payload or is there something else I could be overlooking?

Here is my payload (from VSTS): 
{"buildType": "dev","updater": "$(UpdaterVersion)"}

Payload as shown in VSTS:
![image](https://user-images.githubusercontent.com/5760906/43539972-6dfb8d90-9594-11e8-953b-e0f6197b5ee6.png)

And finally the error I get from the response:

> START RequestId: 05f71cd0-95b5-11e8-9808-a96e749a880c Version: $LATEST
2018-08-01T18:02:15.743Z	05f71cd0-95b5-11e8-9808-a96e749a880c	{"buildType\": \"dev\",\"updater\": \"1.0.0.0\"}
2018-08-01T18:02:15.904Z	05f71cd0-95b5-11e8-9808-a96e749a880c	Error parsing data
2018-08-01T18:02:15.923Z	05f71cd0-95b5-11e8-9808-a96e749a880c	Unable to update tables. Error JSON: {
  "message": "ExpressionAttributeValues must not be empty",
  "code": "ValidationException",
  "time": "2018-08-01T18:02:15.904Z",
  "requestId": "52VGEP89QPI6HE5T0F8FG3NV67VV4KQNSO5AEMVJF66Q9ASUAAJG",
  "statusCode": 400,
  "retryable": false,
  "retryDelay": 2.9687364948105976
}
END RequestId: 05f71cd0-95b5-11e8-9808-a96e749a880c
REPORT RequestId: 05f71cd0-95b5-11e8-9808-a96e749a880c	Duration: 228.99 ms	Billed Duration: 300 ms 	Memory Size: 128 MB	Max Memory Used: 34 MB	

Edit: The payload above works on Postman and through my API that calls the same function through API Gateway.

**Comment by awschristou** [comment]
Would it be possible to compare the payloads you're passing to DynamoDB when the Lambda is called through VSTS or Postman?

**Comment by tastydew** [comment]
I haven't been on this project for quite some time so I cannot reproduce anything related to this issue. I should probably close this...
