### ISSUE TITLE
[Bug?] Upload to S3 is success, but the bucket continues empty

### ISSUE THREAD

**Issue by dulcetti** [aws/aws-vsts-tools#93]
Hi.

I'm trying to configure the Release of a Project, but when the files are uploaded to S3, show the success tasks:
![success](https://user-images.githubusercontent.com/29564/43554258-cd7d40ee-95c9-11e8-931d-5dab3a0f4f55.png)

But, the bucket of S3 is empty after the Upload:
![empty](https://user-images.githubusercontent.com/29564/43554277-e78f4590-95c9-11e8-9507-7d866f8624a5.png)

Anybody have a suggestion of a some configuration?

Regards.

**Comment by tastydew** [comment]
If you are using any variables for your upload I would be sure to check that they are correct, including spacing and special characters. Also, make sure the locations of your artifacts are correct. Sometimes an extra or missing "/" can be the culprit.

**Comment by dulcetti** [comment]
I don't use variables on this Release.

Well, I don't know, but I think the trouble can stay on the Directory or permissions, because the log don't list the files:
![upload S3](https://user-images.githubusercontent.com/29564/43591374-95b9b0b8-9649-11e8-85f7-6033254e7580.png)

On the example of `AWS S3 Upload` show a zip file on the list of directory files. But I don't know if is a problem

**Comment by tastydew** [comment]
Go into your variables for your release definition and use the following

![image](https://user-images.githubusercontent.com/5760906/43593423-b48888f6-9645-11e8-911c-34399e6a4987.png)


and in your AWS Upload task, enable both of these settings

![image](https://user-images.githubusercontent.com/5760906/43593494-e7eae68a-9645-11e8-84ea-84c9210da84b.png)


Then try running your release again. You should get much more information in the logs as to what is going on...

**Comment by JeffRausch** [comment]
It doesn't look like it's finding any files to load to S3.  If it actually uploads files you should also see entries like the following in your log:

> Uploading matched file SOMEPATH, content type...
Completed upload of SOMEPATH to S3PATH

You might want to check your Source Folder and Filename Patterns fields

**Comment by dulcetti** [comment]
Strange. With debug mode on show the results:
```
2018-08-02T16:44:35.7150291Z ##[debug]164 results
2018-08-02T16:44:35.7163287Z ##[debug]All paths D:\agent_pool_02\_work\r18\a\FOLDER\SUB_FOLDER
2018-08-02T16:44:35.7176661Z ##[debug]patternRoot: 'D:\agent_pool_02\_work\r18\a\FOLDER\SUB_FOLDER'
2018-08-02T16:44:35.7176970Z ##[debug]matchOptions.debug: 'false'
2018-08-02T16:44:35.7177360Z ##[debug]matchOptions.nobrace: 'true'
2018-08-02T16:44:35.7177598Z ##[debug]matchOptions.noglobstar: 'false'
2018-08-02T16:44:35.7177848Z ##[debug]matchOptions.dot: 'true'
2018-08-02T16:44:35.7178175Z ##[debug]matchOptions.noext: 'false'
2018-08-02T16:44:35.7178417Z ##[debug]matchOptions.nocase: 'true'
2018-08-02T16:44:35.7178678Z ##[debug]matchOptions.nonull: 'false'
2018-08-02T16:44:35.7178913Z ##[debug]matchOptions.matchBase: 'false'
2018-08-02T16:44:35.7179169Z ##[debug]matchOptions.nocomment: 'false'
2018-08-02T16:44:35.7179404Z ##[debug]matchOptions.nonegate: 'false'
2018-08-02T16:44:35.7179659Z ##[debug]matchOptions.flipNegate: 'false'
2018-08-02T16:44:35.7179905Z ##[debug]pattern: '**/*'
2018-08-02T16:44:35.7180288Z ##[debug]rooted pattern: 'D:\agent_pool_02\_work\r18\a\FOLDER\SUB_FOLDER\**/*'
2018-08-02T16:44:35.7180593Z ##[debug]applying include pattern against original list
2018-08-02T16:44:35.7249836Z ##[debug]0 matches
2018-08-02T16:44:35.7251911Z ##[debug]0 final results
2018-08-02T16:44:35.7252284Z ##[debug]Matched paths 
2018-08-02T16:44:35.7252513Z ##[debug]Matched files list 
2018-08-02T16:44:35.7252823Z ##[debug]found 0 files
```
Showed all the folders and files, but the rooted pattern make 0 final results. I tried put the `Filename Patterns` with `**\*` because of default of Windows folder in cmd, but don't work too.

**Comment by dulcetti** [comment]
I can put files on S3 with `write-s3object` inside the Agent Pool. So, permission is ok.

**Comment by JeffRausch** [comment]
It's not even attempting to write to S3.  The bottom of your log shows 0 matches, and "found 0 files" so there are no files that were even tried to be loaded.
First make sure there are files in your folder "D:\agent_pool_02\_work\r18\a\FOLDER\SUB_FOLDER", I assume there is since the first line in the log you provided shows "164 results" which I believe is from the folder scan of the path you provide.
Then I would play around with the glob pattern.  Maybe try just "*" or an actual path to one of the files in that folder, e.g. if "test.txt" exists in the root of the folder "SUB_FOLDER" then try "test.txt" for the glob pattern.  **/* _should_ work so I'm not sure why it's not matching anything.  I have "**/*.zip" to match some zip files that exist in the root of my folder.

**Comment by dulcetti** [comment]
@JeffRausch I tried `Filename Patterns` with *, **, **\* and **/*.

I tried now with `index.html` and return 0 results, but in the show the file:
`2018-08-09T20:03:50.3483712Z ##[debug]  D:\agent_pool_01\_work\r28\a\FOLDER\SUB_FOLDER\index.html (file)`

And the `Filename Patterns` show the same folder, but with 0 results =/
`2018-08-09T20:03:50.3544441Z ##[debug]rooted pattern: 'D:\agent_pool_01\_work\r28\a\FOLDER\SUB_FOLDER\index.html'`

**Comment by AndrejsAbrickis** [comment]
Hi @dulcetti . I've just had a similar issue with the AWS S3 Upload tasks on Azure DevOps. The cause for us was the `[]` and white space in our source path. We had defined it like this `source-path [PROD]` which resulted in a successful status of the upload but the bucket was still empty. After changing the source path to `source-path-PROD` we were able to upload it to S3.

**Comment by dulcetti** [comment]
Hi @AndrejsAbrickis. Now I am using the task `AWS Tools for Windows PowerShell Script` with code and now works :)

Thanks.

**Comment by dannybarrientos** [comment]
Hi @dulcetti,  @AndrejsAbrickis  How do I manage to upload the files, which contain several folders / subfolder / subfolder / Subcaperta / Subfolder.index?

Thanks

**Comment by dulcetti** [comment]
@dannybarrientos well, I put the follow code:
```
write-s3object -BucketName BUCKET_NAME_ON_S3 -Folder "$(System.DefaultWorkingDirectory)\PATHWAY_WHERE_FILES_ARE" -Recurse -KeyPrefix "\"
```

With `-Recurse`, the content is uploaded recursly
