### ISSUE TITLE
RunAWSPowerShellModuleScript.ps1 task broken when no AWS_Region variable is set pipeline variables

### ISSUE THREAD

**Issue by hansterwal** [aws/aws-vsts-tools#94]
Hi,

In our pipelines we have specified the regionName in the tasks themselves without using an pipeline variable. This works with tag: [1.0.21](https://github.com/aws/aws-vsts-tools/blob/1.0.21/Tasks/AWSPowerShellModuleScript/RunAWSPowerShellModuleScript.ps1) because it is read from the vstsinput field "regionName" on line 37 and is added set to the $env:AWS_Region on line 57.

In the current version with tag [1.1.0](https://github.com/aws/aws-vsts-tools/blob/1.1.0/Tasks/AWSPowerShellModuleScript/RunAWSPowerShellModuleScript.ps1) these steps are put in later which in results in the following stack trace:

```
Configuring task To use role-scoped credentials from specified endpoint Credentials obtained from the supplied key parameters
Leaving D : \a\_tasks\AWSPowerShellModuleScript_37dda93c-8427-4372-9b7b-9b6e10f3f744\1.1.0\RunAWSPowerShellModuleScript.ps1.
Caught exception from task script.Error record
Use-STSRole : No region specified Or obtained from persisted/shell defaults.
At D : \a\_tasks\AWSPowerShellModuleScript_37dda93c-8427-4372-9b7b-9b6e10f3f744\1.1.0\RunAWSPowerShellModuleScript.ps1:109 char:35
            $assumeRoleResponse = Use-STSRole @assumeRoleParameters
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : InvalidOperation :   (Amazon.PowerShe...seSTSRoleCmdlet:UseSTSRoleCmdlet) [Use-STSRole], In    validOperationException
     FullyQualifiedErrorId : InvalidOperationException, mazon.PowerShell.Cmdlets.STS.UseSTSRoleCmdlet
 
Script stack trace
at <ScriptBlock>, D:\a\_tasks\AWSPowerShellModuleScript_37dda93c-8427-4372-9b7b-9b6e10f3f744\1.1.0\RunAWSPowerShellModuleScript.ps1: line 109
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, <No file>: line 22
at <ScriptBlock>, <No file>: line 18
at <ScriptBlock>, <No file>: line 1
Exception
System.InvalidOperationException: **No region specified Or obtained from persisted/shell defaults.**
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
**No region specified Or obtained from persisted/shell defaults.**
```
Are we missing something or is this a bug?

We have added the variable AWS_Region to our release pipeline to mitigate the problem for now.

**Comment by steveataws** [comment]
Sorry, this is a bug introduced in the 1.1.0 release where in a refactor of the region code as part of the overall changes to make credentials and region specification more flexible I missed the embedded use of Use-STSRole in the credentials code. My integration tests didn't catch it as they run on EC2 and as a result of the new flexibility automatically pick up region data from the EC2 instance metadata.

I'm cutting a patch release now, should be available shortly.

**Comment by hansterwal** [comment]
Thank you!

**Comment by steveataws** [comment]
v1.1.1 is now released. 

Apologies again for the inconvenience, if you have any further issues with the task feel free to reopen the issue and I'll take a look.
