### ISSUE TITLE
InvalidClientTokenId error after 1.1.0 update

### ISSUE THREAD

**Issue by kunalpatil3017** [aws/aws-vsts-tools#96]
We are using the AWS CLI plugin to validate the Cloud formation template, It was working as per the requirement till Thursday 2nd august 
Since that day it throws the following error 
![image](https://user-images.githubusercontent.com/22319145/43828182-6638ebea-9b19-11e8-98a6-3c961c2c7982.png)
So ServiceTokenID which is required while fetching credentials from Role is still reflecting old TokenID so AWS STS service throwing an error 
It was working earlier but it stopped working after 2nd of August 2018
That is the exact date where they publish below changes
, https://github.com/aws/aws-vsts-tools/blob/develop/CHANGELOG.md refer 1.1.0 (2018-08-02)
so as per the changelog Service endpoint is now optional
Can some one help us or raise this to right person

**Comment by steveataws** [comment]
You've come to the right place and I'm taking a look.

Based on a preliminary glance at the commits on the cli task itself I don't see any change in the variables (access key, secret key, session token) that are set in the process we launch for the cli; the core of the change was to move getting the generated credentials in the first instance into code shared with all the other tasks.

Are any other tasks showing similar errors for you around the session token? I assume you've set up an assume-role based service endpoint?

**Comment by steveataws** [comment]
I think I see the problem now; the core code we use to obtain the credentials also caches them so if a build runs long enough that it spans token expiry, the old token would be supplied to the task.

I'm testing a fix now that removes the caching (since it buys us nothing) and will release 1.1.3 as soon as testing completes.

**Comment by steveataws** [comment]
@kunalpatil3017, I found two issues in the end - one where an old token could be held onto and another (once I removed the caching) where if one of our other tasks had not been run first, the initial assume role credentials did not get seeded.

I've just published v1.1.3 to the marketplace, hopefully this resolves your issue. I'll leave the issue open overnight, can you let me know how you get on? Thanks.

**Comment by kunalpatil3017** [comment]
Hey @steveataws  Thanks for update 
I have just checked and it is working now thanks for the update 
but there is an another issue i found should i raise as new issue or update in the same

**Comment by steveataws** [comment]
@kunalpatil3017, thanks for  letting me know the original issue is resolved. Feel free to raise a new issue on the other problem you've run into.
